import type {Express,Request,Response} from 'express';
import crypto from 'crypto';
import {pool} from './db.js';

type User={id:string;name:string;role:string};
type Deps={requireUser:(req:Request,res:Response)=>Promise<User|null>};
const code=(p:string)=>`${p}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`;

export async function migrateCampaignEngine(){await pool.query(`
create table if not exists audience_databases(
 id uuid primary key default gen_random_uuid(),db_code text not null unique,name text not null,source text,status text not null default 'active',created_by uuid references operators(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists audience_database_members(
 database_id uuid not null references audience_databases(id) on delete cascade,customer_id uuid not null references customers(id) on delete cascade,consent_snapshot jsonb not null default '{}',eligible boolean not null default true,exclusion_reason text,created_at timestamptz not null default now(),primary key(database_id,customer_id));
create table if not exists chat_templates(
 id uuid primary key default gen_random_uuid(),tc_code text not null unique,name text not null,meta_template_name text,language text not null default 'id',category text,status text not null default 'draft',approved boolean not null default false,body_preview text,variables jsonb not null default '[]',created_by uuid references operators(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists campaigns(
 id uuid primary key default gen_random_uuid(),campaign_code text not null unique,name text not null,group_id uuid not null references whatsapp_groups(id),database_id uuid not null references audience_databases(id),template_id uuid not null references chat_templates(id),status text not null default 'draft',timezone text not null default 'Asia/Jakarta',business_start time not null default '09:00',business_end time not null default '17:00',frequency_cap_hours int not null default 24,pacing_mode text not null default 'adaptive',base_interval_seconds int not null default 20,created_by uuid references operators(id),approved_by uuid references operators(id),approved_at timestamptz,started_at timestamptz,paused_at timestamptz,completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists campaign_queue(
 id uuid primary key default gen_random_uuid(),campaign_id uuid not null references campaigns(id) on delete cascade,customer_id uuid not null references customers(id) on delete cascade,sender_id uuid references whatsapp_accounts(id),status text not null default 'queued',scheduled_at timestamptz,provider_message_id text,attempt_count int not null default 0,blocked_reason text,sent_at timestamptz,delivered_at timestamptz,read_at timestamptz,replied_at timestamptz,failed_at timestamptz,last_error text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(campaign_id,customer_id));
create table if not exists campaign_events(id uuid primary key default gen_random_uuid(),campaign_id uuid not null references campaigns(id) on delete cascade,event_type text not null,actor_id uuid references operators(id),payload jsonb not null default '{}',created_at timestamptz not null default now());
create index if not exists idx_campaign_queue_due on campaign_queue(campaign_id,status,scheduled_at);
create index if not exists idx_campaign_queue_sender on campaign_queue(sender_id,status,scheduled_at);
`)}

async function requireManager(req:Request,res:Response,deps:Deps){const u=await deps.requireUser(req,res);if(!u)return null;if(!['admin','supervisor'].includes(u.role)){res.status(403).json({error:'forbidden'});return null}return u}

export async function createCampaignFromCommand(a:any,userId:string){const g=(await pool.query('select id from whatsapp_groups where id=$1 or group_code=$1',[a.group_id])).rows[0];const d=(await pool.query('select id from audience_databases where id=$1 or db_code=$1',[a.database_id])).rows[0];const t=(await pool.query('select id,approved,status from chat_templates where id=$1 or tc_code=$1',[a.template_id])).rows[0];if(!g)throw new Error('group_not_found');if(!d)throw new Error('database_not_found');if(!t)throw new Error('template_not_found');const q=await pool.query(`insert into campaigns(campaign_code,name,group_id,database_id,template_id,timezone,business_start,business_end,frequency_cap_hours,pacing_mode,base_interval_seconds,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,'adaptive',$10,$11) returning *`,[code('CMP'),a.name||'AI campaign',g.id,d.id,t.id,a.timezone||'Asia/Jakarta',a.business_start||'09:00',a.business_end||'17:00',Math.max(1,Number(a.frequency_cap_hours)||24),Math.max(5,Number(a.base_interval_seconds)||20),userId]);return q.rows[0]}

async function eligibleSenders(groupId:string){return (await pool.query(`select wa.id,wa.name,wa.health_score,gm.priority,gm.is_primary,count(c.id) filter(where c.status='open')::int workload from whatsapp_group_members gm join whatsapp_accounts wa on wa.id=gm.whatsapp_account_id left join conversations c on c.whatsapp_account_id=wa.id join whatsapp_groups g on g.id=gm.group_id where gm.group_id=$1 and g.status='active' and wa.status in('active','healthy') and wa.health_score>=g.min_health_score group by wa.id,gm.priority,gm.is_primary order by gm.is_primary desc,wa.health_score desc,workload asc,gm.priority asc`,[groupId])).rows}

export async function prepareCampaignQueue(campaignId:string){const c=(await pool.query(`select c.*,t.approved template_approved,t.status template_status from campaigns c join chat_templates t on t.id=c.template_id where c.id=$1 or c.campaign_code=$1`,[campaignId])).rows[0];if(!c)throw new Error('campaign_not_found');const senders=await eligibleSenders(c.group_id);if(!senders.length)throw new Error('no_eligible_senders');const members=(await pool.query(`select m.customer_id,cu.assigned_whatsapp_id,cu.opt_in,cu.do_not_contact from audience_database_members m join customers cu on cu.id=m.customer_id where m.database_id=$1`,[c.database_id])).rows;let queued=0,blocked=0;const nextAt=new Map<string,number>();const start=Date.now();for(let i=0;i<members.length;i++){const m=members[i];let reason:string|null=null;if(!m.opt_in)reason='no_opt_in';else if(m.do_not_contact)reason='do_not_contact';else{const recent=await pool.query(`select 1 from campaign_queue q join campaigns c2 on c2.id=q.campaign_id where q.customer_id=$1 and q.sent_at>now()-($2||' hours')::interval limit 1`,[m.customer_id,String(c.frequency_cap_hours)]);if(recent.rowCount)reason='frequency_cap'}if(reason){await pool.query(`insert into campaign_queue(campaign_id,customer_id,status,blocked_reason) values($1,$2,'blocked',$3) on conflict(campaign_id,customer_id) do update set status='blocked',blocked_reason=excluded.blocked_reason,updated_at=now()`,[c.id,m.customer_id,reason]);blocked++;continue}let s=senders.find((x:any)=>x.id===m.assigned_whatsapp_id)||senders[i%senders.length];const healthFactor=Math.max(.8,Math.min(1.8,100/Math.max(40,Number(s.health_score)||60)));const spacing=Math.round(Number(c.base_interval_seconds)*healthFactor)*1000;const prev=nextAt.get(s.id)||start;const when=Math.max(prev,start);nextAt.set(s.id,when+spacing);await pool.query(`insert into campaign_queue(campaign_id,customer_id,sender_id,status,scheduled_at,blocked_reason) values($1,$2,$3,'queued',to_timestamp($4/1000.0),null) on conflict(campaign_id,customer_id) do update set sender_id=excluded.sender_id,status='queued',scheduled_at=excluded.scheduled_at,blocked_reason=null,updated_at=now()`,[c.id,m.customer_id,s.id,when]);queued++}await pool.query(`insert into campaign_events(campaign_id,event_type,payload) values($1,'queue_prepared',$2)`,[c.id,JSON.stringify({queued,blocked,senders:senders.length})]);return{campaign_id:c.id,queued,blocked,senders}}

export function registerCampaignRoutes(app:Express,deps:Deps){
 app.get('/api/v1/campaigns/summary',async(req,res)=>{const u=await deps.requireUser(req,res);if(!u)return;const q=await pool.query(`select count(*)::int total,count(*) filter(where status='running')::int running,count(*) filter(where status='paused')::int paused from campaigns`);const s=await pool.query(`select count(*) filter(where status='queued')::int queued,count(*) filter(where status='blocked')::int blocked,count(*) filter(where status='sent')::int sent,count(*) filter(where status='delivered')::int delivered,count(*) filter(where status='read')::int read,count(*) filter(where status='replied')::int replied from campaign_queue`);res.json({campaigns:q.rows[0],queue:s.rows[0]})});
 app.get('/api/v1/audiences',async(req,res)=>{const u=await deps.requireUser(req,res);if(!u)return;const q=await pool.query(`select d.*,count(m.customer_id)::int records,count(m.customer_id) filter(where m.eligible)::int eligible from audience_databases d left join audience_database_members m on m.database_id=d.id group by d.id order by d.created_at desc`);res.json({items:q.rows})});
 app.post('/api/v1/audiences',async(req,res)=>{const u=await requireManager(req,res,deps);if(!u)return;const name=String(req.body?.name||'').trim();if(!name)return res.status(400).json({error:'name_required'});const d=(await pool.query(`insert into audience_databases(db_code,name,source,created_by) values($1,$2,$3,$4) returning *`,[String(req.body?.db_code||'').trim().toUpperCase()||code('DB'),name,String(req.body?.source||'manual'),u.id])).rows[0];const ids=Array.isArray(req.body?.customer_ids)?req.body.customer_ids:[];for(const id of ids)await pool.query(`insert into audience_database_members(database_id,customer_id,consent_snapshot) select $1,id,jsonb_build_object('opt_in',opt_in,'opt_in_source',opt_in_source,'opt_in_at',opt_in_at,'do_not_contact',do_not_contact) from customers where id=$2 on conflict do nothing`,[d.id,id]);res.status(201).json(d)});
 app.get('/api/v1/chat-templates',async(req,res)=>{const u=await deps.requireUser(req,res);if(!u)return;res.json({items:(await pool.query(`select * from chat_templates order by created_at desc`)).rows})});
 app.post('/api/v1/chat-templates',async(req,res)=>{const u=await requireManager(req,res,deps);if(!u)return;const q=await pool.query(`insert into chat_templates(tc_code,name,meta_template_name,language,category,status,approved,body_preview,variables,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning *`,[String(req.body?.tc_code||'').trim().toUpperCase()||code('TC'),req.body?.name||'Template',req.body?.meta_template_name||null,req.body?.language||'id',req.body?.category||null,req.body?.approved?'approved':'draft',Boolean(req.body?.approved),req.body?.body_preview||null,JSON.stringify(req.body?.variables||[]),u.id]);res.status(201).json(q.rows[0])});
 app.get('/api/v1/campaigns',async(req,res)=>{const u=await deps.requireUser(req,res);if(!u)return;const q=await pool.query(`select c.*,g.group_code,g.name group_name,d.db_code,t.tc_code,t.name template_name,(select count(*) from campaign_queue q where q.campaign_id=c.id)::int queue_total from campaigns c join whatsapp_groups g on g.id=c.group_id join audience_databases d on d.id=c.database_id join chat_templates t on t.id=c.template_id order by c.created_at desc`);res.json({items:q.rows})});
 app.post('/api/v1/campaigns',async(req,res)=>{const u=await requireManager(req,res,deps);if(!u)return;try{res.status(201).json(await createCampaignFromCommand(req.body,u.id))}catch(e:any){res.status(400).json({error:e.message})}});
 app.post('/api/v1/campaigns/:id/prepare',async(req,res)=>{const u=await requireManager(req,res,deps);if(!u)return;try{res.json(await prepareCampaignQueue(req.params.id))}catch(e:any){res.status(400).json({error:e.message})}});
 app.post('/api/v1/campaigns/:id/approve',async(req,res)=>{const u=await requireManager(req,res,deps);if(!u)return;const q=await pool.query(`update campaigns set status='approved',approved_by=$2,approved_at=now(),updated_at=now() where id=$1 or campaign_code=$1 returning *`,[req.params.id,u.id]);res.json(q.rows[0]||{})});
 app.post('/api/v1/campaigns/:id/:action',async(req,res)=>{const u=await requireManager(req,res,deps);if(!u)return;const a=req.params.action;if(!['start','pause','resume','abort'].includes(a))return res.status(400).json({error:'invalid_action'});const map:any={start:'running',pause:'paused',resume:'running',abort:'aborted'};const q=await pool.query(`update campaigns set status=$2,started_at=case when $2='running' and started_at is null then now() else started_at end,paused_at=case when $2='paused' then now() else paused_at end,updated_at=now() where id=$1 or campaign_code=$1 returning *`,[req.params.id,map[a]]);res.json(q.rows[0]||{})});
 app.get('/api/v1/campaigns/:id/queue',async(req,res)=>{const u=await deps.requireUser(req,res);if(!u)return;const q=await pool.query(`select q.*,cu.name customer_name,cu.phone,wa.name sender_name,wa.phone sender_phone from campaign_queue q join customers cu on cu.id=q.customer_id left join whatsapp_accounts wa on wa.id=q.sender_id where q.campaign_id=(select id from campaigns where id=$1 or campaign_code=$1) order by q.scheduled_at nulls last limit 1000`,[req.params.id]);res.json({items:q.rows})});
}
