import type{Express,Request,Response}from'express';import{pool}from'./db.js';
type User={id:string;name:string;role:string;department?:string};type Deps={requireUser:(req:Request,res:Response)=>Promise<User|null>};
const model=process.env.OPENAI_COMMAND_MODEL||process.env.OPENAI_MODEL||'gpt-5.6-luna';
const tools:any[]=[
 {type:'function',name:'search_customers',description:'Search RelayOS CRM customers by name phone email and optional temperature.',strict:true,parameters:{type:'object',properties:{query:{type:'string'},temperature:{type:['string','null'],enum:['hot','warm','cold',null]},limit:{type:'integer',minimum:1,maximum:20}},required:['query','temperature','limit'],additionalProperties:false}},
 {type:'function',name:'customer_360',description:'Load full CRM context for a customer by UUID.',strict:true,parameters:{type:'object',properties:{customer_id:{type:'string'}},required:['customer_id'],additionalProperties:false}},
 {type:'function',name:'hot_leads',description:'List hottest leads by buying intent and lead score.',strict:true,parameters:{type:'object',properties:{limit:{type:'integer',minimum:1,maximum:20}},required:['limit'],additionalProperties:false}},
 {type:'function',name:'stale_deals',description:'List open deals that have not been updated for a number of days.',strict:true,parameters:{type:'object',properties:{days:{type:'integer',minimum:1,maximum:365},limit:{type:'integer',minimum:1,maximum:30}},required:['days','limit'],additionalProperties:false}},
 {type:'function',name:'number_health',description:'List WhatsApp sender health status and workload.',strict:true,parameters:{type:'object',properties:{},required:[],additionalProperties:false}},
 {type:'function',name:'create_task',description:'Propose creating a CRM task. This never executes without operator approval.',strict:true,parameters:{type:'object',properties:{title:{type:'string'},description:{type:'string'},customer_id:{type:['string','null']},deal_id:{type:['string','null']},assigned_to:{type:['string','null']},priority:{type:'string',enum:['low','normal','high','urgent']},due_at:{type:['string','null']}},required:['title','description','customer_id','deal_id','assigned_to','priority','due_at'],additionalProperties:false}},
 {type:'function',name:'update_customer_stage',description:'Propose changing a customer lifecycle stage. Requires approval.',strict:true,parameters:{type:'object',properties:{customer_id:{type:'string'},lifecycle_stage:{type:'string'}},required:['customer_id','lifecycle_stage'],additionalProperties:false}},
 {type:'function',name:'prepare_failover',description:'Propose WhatsApp channel failover for an open conversation. Requires approval.',strict:true,parameters:{type:'object',properties:{conversation_id:{type:'string'},whatsapp_account_id:{type:['string','null']},reason:{type:'string'}},required:['conversation_id','whatsapp_account_id','reason'],additionalProperties:false}}
];
export async function migrateCommandCenter(){await pool.query(`create table if not exists command_threads(id uuid primary key default gen_random_uuid(),operator_id uuid not null references operators(id) on delete cascade,title text,status text not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now());create table if not exists command_messages(id uuid primary key default gen_random_uuid(),thread_id uuid not null references command_threads(id) on delete cascade,role text not null,content text not null,metadata jsonb not null default '{}',created_at timestamptz not null default now());create table if not exists command_proposals(id uuid primary key default gen_random_uuid(),thread_id uuid references command_threads(id) on delete set null,operator_id uuid references operators(id),action_type text not null,arguments jsonb not null,status text not null default 'pending',result jsonb,approved_by uuid references operators(id),approved_at timestamptz,executed_at timestamptz,created_at timestamptz not null default now());create index if not exists idx_command_messages_thread on command_messages(thread_id,created_at);create index if not exists idx_command_proposals_operator on command_proposals(operator_id,status,created_at desc);`)}
async function callTool(name:string,a:any,u:User,threadId:string){if(name==='search_customers'){const q=await pool.query(`select id,name,phone,email,lifecycle_stage,lead_score,lead_temperature,owner_id,last_contact_at,next_action_at from customers where ($1='' or coalesce(name,'') ilike '%'||$1||'%' or phone ilike '%'||$1||'%' or coalesce(email,'') ilike '%'||$1||'%') and ($2::text is null or lead_temperature=$2) order by lead_score desc limit $3`,[a.query||'',a.temperature||null,a.limit||10]);return{items:q.rows}}
 if(name==='customer_360'){const [c,d,t,s]=await Promise.all([pool.query('select * from customers where id=$1',[a.customer_id]),pool.query('select id,title,amount,currency,status,probability,ai_health,ai_risk_score,updated_at from crm_deals where customer_id=$1 order by updated_at desc limit 20',[a.customer_id]),pool.query('select id,title,priority,status,due_at from crm_tasks where customer_id=$1 order by created_at desc limit 20',[a.customer_id]),pool.query("select signal_type,severity,title,explanation,created_at from crm_ai_signals where customer_id=$1 and status='active' order by created_at desc limit 20",[a.customer_id])]);return{customer:c.rows[0]||null,deals:d.rows,tasks:t.rows,signals:s.rows}}
 if(name==='hot_leads'){const q=await pool.query(`select id,name,phone,email,lead_score,lead_temperature,ai_buying_intent_score,ai_engagement_score,ai_next_best_action from customers order by coalesce(ai_buying_intent_score,0) desc,lead_score desc limit $1`,[a.limit||10]);return{items:q.rows}}
 if(name==='stale_deals'){const q=await pool.query(`select d.id,d.title,d.amount,d.currency,d.probability,d.status,d.updated_at,c.id customer_id,c.name customer_name from crm_deals d left join customers c on c.id=d.customer_id where d.status='open' and d.updated_at<now()-($1||' days')::interval order by d.amount desc limit $2`,[String(a.days||7),a.limit||20]);return{items:q.rows}}
 if(name==='number_health'){const q=await pool.query(`select wa.id,wa.name,wa.phone,wa.status,wa.health_score,count(cv.id) filter(where cv.status='open')::int open_conversations,wa.last_error from whatsapp_accounts wa left join conversations cv on cv.whatsapp_account_id=wa.id group by wa.id order by wa.health_score desc`);return{items:q.rows}}
 if(['create_task','update_customer_stage','prepare_failover'].includes(name)){const p=(await pool.query(`insert into command_proposals(thread_id,operator_id,action_type,arguments) values($1,$2,$3,$4) returning *`,[threadId,u.id,name,JSON.stringify(a)])).rows[0];return{proposal_created:true,proposal_id:p.id,status:'pending',action_type:name,arguments:a}}
 return{error:'unknown_tool'} }
function outputText(r:any){return String(r?.output_text||'').trim()||String((r?.output||[]).filter((x:any)=>x.type==='message').flatMap((x:any)=>x.content||[]).map((x:any)=>x.text||'').join('\n')).trim()}
async function openai(body:any){const key=process.env.OPENAI_API_KEY;if(!key)throw Object.assign(new Error('OPENAI_API_KEY is not configured'),{code:'ai_not_configured'});const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${key}`,'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||'OpenAI request failed');return d}
export function registerCommandCenterRoutes(app:Express,deps:Deps){
 app.get('/api/v1/command-center/status',async(req,res)=>{const u=await deps.requireUser(req,res);if(!u)return;res.json({ai_available:Boolean(process.env.OPENAI_API_KEY),model,tools:tools.map(x=>x.name)})});
 app.get('/api/v1/command-center/threads',async(req,res)=>{const u=await deps.requireUser(req,res);if(!u)return;const q=await pool.query('select * from command_threads where operator_id=$1 order by updated_at desc limit 30',[u.id]);res.json({items:q.rows})});
 app.get('/api/v1/command-center/threads/:id',async(req,res)=>{const u=await deps.requireUser(req,res);if(!u)return;const t=(await pool.query('select * from command_threads where id=$1 and operator_id=$2',[req.params.id,u.id])).rows[0];if(!t)return res.status(404).json({error:'thread_not_found'});const [m,p]=await Promise.all([pool.query('select * from command_messages where thread_id=$1 order by created_at',[t.id]),pool.query("select * from command_proposals where thread_id=$1 and status='pending' order by created_at desc",[t.id])]);res.json({thread:t,messages:m.rows,proposals:p.rows})});
 app.post('/api/v1/command-center/chat',async(req,res)=>{const u=await deps.requireUser(req,res);if(!u)return;const text=String(req.body?.message||'').trim();if(!text)return res.status(400).json({error:'message_required'});let threadId=String(req.body?.thread_id||'');if(!threadId){const t=(await pool.query('insert into command_threads(operator_id,title) values($1,$2) returning id',[u.id,text.slice(0,70)])).rows[0];threadId=t.id}else{const ok=await pool.query('select 1 from command_threads where id=$1 and operator_id=$2',[threadId,u.id]);if(!ok.rowCount)return res.status(404).json({error:'thread_not_found'})}await pool.query('insert into command_messages(thread_id,role,content) values($1,$2,$3)',[threadId,'user',text]);const hist=(await pool.query('select role,content from command_messages where thread_id=$1 order by created_at desc limit 14',[threadId])).rows.reverse();try{let response=await openai({model,instructions:`You are RelayOS AI Command Center. Operate as an enterprise AI CRM copilot. Current operator: ${u.name} (${u.role}). Use tools instead of inventing CRM facts. Read-only tools may be used freely. Mutation tools only create proposals and MUST be described as pending approval. Never claim an action executed unless a tool result says so. Be concise, operational and use Indonesian unless the operator writes in another language.`,input:hist.map((m:any)=>({role:m.role==='assistant'?'assistant':'user',content:m.content})),tools,tool_choice:'auto'});for(let round=0;round<4;round++){const calls=(response.output||[]).filter((x:any)=>x.type==='function_call');if(!calls.length)break;const outputs=[];for(const c of calls){let args:any={};try{args=JSON.parse(c.arguments||'{}')}catch{}const result=await callTool(c.name,args,u,threadId);outputs.push({type:'function_call_output',call_id:c.call_id,output:JSON.stringify(result)})}response=await openai({model,previous_response_id:response.id,input:outputs,tools,tool_choice:'auto'})}const answer=outputText(response)||'Saya sudah memproses permintaan ini.';await pool.query('insert into command_messages(thread_id,role,content,metadata) values($1,$2,$3,$4)',[threadId,'assistant',answer,JSON.stringify({response_id:response.id,model})]);await pool.query('update command_threads set updated_at=now() where id=$1',[threadId]);const p=await pool.query("select * from command_proposals where thread_id=$1 and status='pending' order by created_at desc",[threadId]);res.json({thread_id:threadId,answer,proposals:p.rows,model})}catch(e:any){res.status(e.code==='ai_not_configured'?503:500).json({error:e.code||'command_center_failed',detail:e.message,thread_id:threadId})}});
 app.post('/api/v1/command-center/proposals/:id/approve',async(req,res)=>{const u=await deps.requireUser(req,res);if(!u)return;const p=(await pool.query("select * from command_proposals where id=$1 and operator_id=$2 and status='pending'",[req.params.id,u.id])).rows[0];if(!p)return res.status(404).json({error:'proposal_not_found'});const a=p.arguments||{};let result:any={};if(p.action_type==='create_task'){const q=await pool.query(`insert into crm_tasks(title,description,customer_id,deal_id,assigned_to,created_by,priority,due_at) values($1,$2,$3,$4,$5,$6,$7,$8) returning *`,[a.title,a.description||null,a.customer_id||null,a.deal_id||null,a.assigned_to||null,u.id,a.priority||'normal',a.due_at||null]);result=q.rows[0]}else if(p.action_type==='update_customer_stage'){const q=await pool.query('update customers set lifecycle_stage=$2,updated_at=now() where id=$1 returning id,name,lifecycle_stage',[a.customer_id,a.lifecycle_stage]);result=q.rows[0]}else if(p.action_type==='prepare_failover'){return res.status(409).json({error:'use_continuity_center_for_failover',continuity_url:'/continuity.html',arguments:a})}else return res.status(400).json({error:'unsupported_action'});await pool.query("update command_proposals set status='executed',approved_by=$2,approved_at=now(),executed_at=now(),result=$3 where id=$1",[p.id,u.id,JSON.stringify(result)]);res.json({ok:true,result})});
 app.post('/api/v1/command-center/proposals/:id/reject',async(req,res)=>{const u=await deps.requireUser(req,res);if(!u)return;await pool.query("update command_proposals set status='rejected',approved_by=$2,approved_at=now() where id=$1 and operator_id=$2 and status='pending'",[req.params.id,u.id]);res.json({ok:true})});
}
