import type {Express,Request,Response} from 'express';
import {pool} from './db.js';

type User={id:string;name:string;role:string;department?:string};
type Deps={requireUser:(req:Request,res:Response)=>Promise<User|null>};

function clamp(n:number,min=0,max=100){return Math.max(min,Math.min(max,n))}
function str(v:any){return String(v??'').trim()}
function arr(v:any){return Array.isArray(v)?v.map(String):String(v||'').split(',').map(x=>x.trim()).filter(Boolean)}

export async function migrateCrm(){
 await pool.query(`
  alter table customers add column if not exists email text;
  alter table customers add column if not exists lifecycle_stage text not null default 'lead';
  alter table customers add column if not exists lead_score int not null default 0;
  alter table customers add column if not exists lead_temperature text not null default 'cold';
  alter table customers add column if not exists owner_id uuid references operators(id);
  alter table customers add column if not exists company_id uuid;
  alter table customers add column if not exists last_contact_at timestamptz;
  alter table customers add column if not exists next_action_at timestamptz;
  alter table customers add column if not exists custom_fields jsonb not null default '{}';

  create table if not exists crm_companies(
    id uuid primary key default gen_random_uuid(),name text not null,domain text,industry text,phone text,email text,address text,city text,country text,owner_id uuid references operators(id),tags text[] not null default '{}',custom_fields jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now()
  );
  create unique index if not exists uq_crm_company_domain on crm_companies(lower(domain)) where domain is not null and domain<>'';
  do $$ begin if not exists(select 1 from pg_constraint where conname='customers_company_fk') then alter table customers add constraint customers_company_fk foreign key(company_id) references crm_companies(id) on delete set null; end if; end $$;

  create table if not exists crm_pipelines(
    id uuid primary key default gen_random_uuid(),name text not null,department text,is_default boolean not null default false,created_at timestamptz not null default now()
  );
  create table if not exists crm_pipeline_stages(
    id uuid primary key default gen_random_uuid(),pipeline_id uuid not null references crm_pipelines(id) on delete cascade,name text not null,position int not null,probability int not null default 0 check(probability between 0 and 100),stage_type text not null default 'open' check(stage_type in ('open','won','lost')),created_at timestamptz not null default now(),unique(pipeline_id,position)
  );
  create table if not exists crm_deals(
    id uuid primary key default gen_random_uuid(),title text not null,customer_id uuid references customers(id) on delete set null,company_id uuid references crm_companies(id) on delete set null,pipeline_id uuid not null references crm_pipelines(id),stage_id uuid not null references crm_pipeline_stages(id),owner_id uuid references operators(id),amount numeric(18,2) not null default 0,currency text not null default 'IDR',probability int not null default 0,expected_close_at date,status text not null default 'open' check(status in ('open','won','lost')),source text,loss_reason text,ai_health text not null default 'unknown',ai_risk_score int not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),closed_at timestamptz
  );
  create table if not exists crm_activities(
    id uuid primary key default gen_random_uuid(),customer_id uuid references customers(id) on delete cascade,company_id uuid references crm_companies(id) on delete cascade,deal_id uuid references crm_deals(id) on delete cascade,conversation_id uuid references conversations(id) on delete set null,operator_id uuid references operators(id),activity_type text not null,subject text,body text,channel text,status text not null default 'completed',due_at timestamptz,completed_at timestamptz,metadata jsonb not null default '{}',created_at timestamptz not null default now()
  );
  create table if not exists crm_tasks(
    id uuid primary key default gen_random_uuid(),title text not null,description text,customer_id uuid references customers(id) on delete cascade,deal_id uuid references crm_deals(id) on delete cascade,assigned_to uuid references operators(id),created_by uuid references operators(id),priority text not null default 'normal',status text not null default 'open' check(status in ('open','in_progress','done','cancelled')),due_at timestamptz,completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
  );
  create table if not exists crm_ai_signals(
    id uuid primary key default gen_random_uuid(),customer_id uuid references customers(id) on delete cascade,deal_id uuid references crm_deals(id) on delete cascade,signal_type text not null,severity text not null default 'info',score_delta int not null default 0,title text not null,explanation text,evidence jsonb not null default '{}',status text not null default 'active',created_at timestamptz not null default now(),expires_at timestamptz
  );
  create table if not exists crm_segments(
    id uuid primary key default gen_random_uuid(),name text not null,description text,filter_json jsonb not null default '{}',is_dynamic boolean not null default true,created_by uuid references operators(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now()
  );
  create table if not exists crm_audit_events(
    id uuid primary key default gen_random_uuid(),entity_type text not null,entity_id uuid,event_type text not null,actor_id uuid references operators(id),payload jsonb not null default '{}',created_at timestamptz not null default now()
  );
  create index if not exists idx_customers_owner_score on customers(owner_id,lead_score desc);
  create index if not exists idx_customers_lifecycle on customers(lifecycle_stage,updated_at desc);
  create index if not exists idx_deals_stage on crm_deals(stage_id,status,updated_at desc);
  create index if not exists idx_activities_customer on crm_activities(customer_id,created_at desc);
  create index if not exists idx_tasks_assignee on crm_tasks(assigned_to,status,due_at);
  create index if not exists idx_ai_signals_customer on crm_ai_signals(customer_id,status,created_at desc);
 `);
 const pipeline=await pool.query(`insert into crm_pipelines(name,department,is_default) select 'Default Sales','Sales',true where not exists(select 1 from crm_pipelines where is_default=true) returning id`);
 let pid=pipeline.rows[0]?.id;
 if(!pid)pid=(await pool.query('select id from crm_pipelines where is_default=true order by created_at limit 1')).rows[0]?.id;
 if(pid){
   const stages=[['New Lead',1,10,'open'],['Qualified',2,30,'open'],['Proposal',3,55,'open'],['Negotiation',4,75,'open'],['Won',5,100,'won'],['Lost',6,0,'lost']];
   for(const s of stages)await pool.query(`insert into crm_pipeline_stages(pipeline_id,name,position,probability,stage_type) values($1,$2,$3,$4,$5) on conflict(pipeline_id,position) do nothing`,[pid,...s]);
 }
}

async function audit(entityType:string,entityId:string,eventType:string,actorId:string,payload:any={}){await pool.query('insert into crm_audit_events(entity_type,entity_id,event_type,actor_id,payload) values($1,$2,$3,$4,$5)',[entityType,entityId,eventType,actorId,JSON.stringify(payload)])}

async function recomputeCustomerScore(customerId:string){
 const [c,conv,deals,signals,acts]=await Promise.all([
   pool.query('select * from customers where id=$1',[customerId]),
   pool.query("select count(*)::int n,max(last_message_at) last_at from conversations where customer_id=$1",[customerId]),
   pool.query("select count(*) filter(where status='open')::int open,count(*) filter(where status='won')::int won,coalesce(sum(amount) filter(where status='won'),0)::numeric won_value from crm_deals where customer_id=$1",[customerId]),
   pool.query("select coalesce(sum(score_delta),0)::int delta from crm_ai_signals where customer_id=$1 and status='active' and (expires_at is null or expires_at>now())",[customerId]),
   pool.query("select count(*)::int n from crm_activities where customer_id=$1 and created_at>now()-interval '30 days'",[customerId])
 ]);
 const x=c.rows[0];if(!x)return null;
 let score=0;if(x.opt_in)score+=8;if(x.email)score+=5;if(x.name)score+=4;score+=Math.min(20,conv.rows[0].n*3);score+=Math.min(15,acts.rows[0].n*2);score+=Math.min(20,deals.rows[0].open*7);score+=Math.min(25,deals.rows[0].won*12);score+=Number(signals.rows[0].delta||0);if(x.do_not_contact)score-=40;
 score=clamp(score);const temp=score>=70?'hot':score>=40?'warm':'cold';await pool.query('update customers set lead_score=$2,lead_temperature=$3,updated_at=now() where id=$1',[customerId,score,temp]);return{score,temperature:temp};
}

export function registerCrmRoutes(app:Express,deps:Deps){
 const user=(req:Request,res:Response)=>deps.requireUser(req,res);
 app.get('/api/v1/crm/dashboard',async(req,res)=>{const u=await user(req,res);if(!u)return;const [contacts,hot,deals,pipeline,tasks,activities]=await Promise.all([
  pool.query('select count(*)::int n from customers'),pool.query("select count(*)::int n from customers where lead_temperature='hot'"),pool.query("select count(*)::int n,coalesce(sum(amount),0)::numeric value from crm_deals where status='open'"),pool.query("select coalesce(sum(amount*probability/100.0),0)::numeric weighted from crm_deals where status='open'"),pool.query("select count(*)::int n from crm_tasks where status in('open','in_progress') and due_at<now()+interval '24 hours'"),pool.query("select count(*)::int n from crm_activities where created_at>now()-interval '24 hours'")]);res.json({contacts:contacts.rows[0].n,hot_leads:hot.rows[0].n,open_deals:deals.rows[0].n,pipeline_value:Number(deals.rows[0].value),weighted_pipeline:Number(pipeline.rows[0].weighted),tasks_due:tasks.rows[0].n,activities24h:activities.rows[0].n})});

 app.get('/api/v1/crm/contacts',async(req,res)=>{const u=await user(req,res);if(!u)return;const q=str(req.query.q),limit=Math.min(Number(req.query.limit)||100,500);const rows=await pool.query(`select c.*,o.name owner_name,co.name company_name,(select count(*)::int from crm_deals d where d.customer_id=c.id and d.status='open') open_deals,(select max(created_at) from crm_activities a where a.customer_id=c.id) last_activity_at from customers c left join operators o on o.id=c.owner_id left join crm_companies co on co.id=c.company_id where ($1='' or c.name ilike '%'||$1||'%' or c.phone ilike '%'||$1||'%' or c.email ilike '%'||$1||'%') order by c.lead_score desc,c.updated_at desc limit $2`,[q,limit]);res.json({items:rows.rows})});
 app.get('/api/v1/crm/contacts/:id',async(req,res)=>{const u=await user(req,res);if(!u)return;const [c,deals,acts,tasks,signals,convs]=await Promise.all([pool.query(`select c.*,o.name owner_name,co.name company_name from customers c left join operators o on o.id=c.owner_id left join crm_companies co on co.id=c.company_id where c.id=$1`,[req.params.id]),pool.query(`select d.*,s.name stage_name,p.name pipeline_name,o.name owner_name from crm_deals d join crm_pipeline_stages s on s.id=d.stage_id join crm_pipelines p on p.id=d.pipeline_id left join operators o on o.id=d.owner_id where d.customer_id=$1 order by d.updated_at desc`,[req.params.id]),pool.query('select a.*,o.name operator_name from crm_activities a left join operators o on o.id=a.operator_id where a.customer_id=$1 order by a.created_at desc limit 100',[req.params.id]),pool.query('select t.*,o.name assigned_name from crm_tasks t left join operators o on o.id=t.assigned_to where t.customer_id=$1 order by t.status,t.due_at nulls last',[req.params.id]),pool.query("select * from crm_ai_signals where customer_id=$1 and status='active' order by created_at desc",[req.params.id]),pool.query('select id,status,intent,last_message_at,unread_count,priority,escalation_status from conversations where customer_id=$1 order by last_message_at desc limit 50',[req.params.id])]);if(!c.rows[0])return res.status(404).json({error:'contact_not_found'});res.json({contact:c.rows[0],deals:deals.rows,activities:acts.rows,tasks:tasks.rows,signals:signals.rows,conversations:convs.rows})});
 app.patch('/api/v1/crm/contacts/:id',async(req,res)=>{const u=await user(req,res);if(!u)return;const q=await pool.query(`update customers set name=coalesce($2,name),email=coalesce($3,email),lifecycle_stage=coalesce($4,lifecycle_stage),owner_id=coalesce($5::uuid,owner_id),company_id=coalesce($6::uuid,company_id),tags=case when $7::text[] is null then tags else $7 end,next_action_at=coalesce($8::timestamptz,next_action_at),custom_fields=custom_fields||$9::jsonb,updated_at=now() where id=$1 returning *`,[req.params.id,str(req.body?.name)||null,str(req.body?.email)||null,str(req.body?.lifecycle_stage)||null,str(req.body?.owner_id)||null,str(req.body?.company_id)||null,req.body?.tags?arr(req.body.tags):null,req.body?.next_action_at||null,JSON.stringify(req.body?.custom_fields||{})]);if(!q.rows[0])return res.status(404).json({error:'contact_not_found'});await audit('contact',req.params.id,'updated',u.id,req.body);await recomputeCustomerScore(req.params.id);res.json(q.rows[0])});
 app.post('/api/v1/crm/contacts/:id/rescore',async(req,res)=>{const u=await user(req,res);if(!u)return;res.json(await recomputeCustomerScore(req.params.id))});

 app.get('/api/v1/crm/companies',async(req,res)=>{const u=await user(req,res);if(!u)return;const q=await pool.query(`select co.*,o.name owner_name,count(c.id)::int contacts from crm_companies co left join operators o on o.id=co.owner_id left join customers c on c.company_id=co.id group by co.id,o.name order by co.updated_at desc`);res.json({items:q.rows})});
 app.post('/api/v1/crm/companies',async(req,res)=>{const u=await user(req,res);if(!u)return;const name=str(req.body?.name);if(!name)return res.status(400).json({error:'name_required'});const q=await pool.query(`insert into crm_companies(name,domain,industry,phone,email,address,city,country,owner_id,tags,custom_fields) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning *`,[name,str(req.body?.domain)||null,str(req.body?.industry)||null,str(req.body?.phone)||null,str(req.body?.email)||null,str(req.body?.address)||null,str(req.body?.city)||null,str(req.body?.country)||null,str(req.body?.owner_id)||null,arr(req.body?.tags),JSON.stringify(req.body?.custom_fields||{})]);await audit('company',q.rows[0].id,'created',u.id);res.status(201).json(q.rows[0])});

 app.get('/api/v1/crm/pipelines',async(req,res)=>{const u=await user(req,res);if(!u)return;const p=await pool.query('select * from crm_pipelines order by is_default desc,name');const stages=await pool.query('select * from crm_pipeline_stages order by pipeline_id,position');res.json({pipelines:p.rows,stages:stages.rows})});
 app.get('/api/v1/crm/deals',async(req,res)=>{const u=await user(req,res);if(!u)return;const q=await pool.query(`select d.*,s.name stage_name,s.position,s.stage_type,p.name pipeline_name,c.name customer_name,c.phone customer_phone,co.name company_name,o.name owner_name from crm_deals d join crm_pipeline_stages s on s.id=d.stage_id join crm_pipelines p on p.id=d.pipeline_id left join customers c on c.id=d.customer_id left join crm_companies co on co.id=d.company_id left join operators o on o.id=d.owner_id order by p.id,s.position,d.updated_at desc`);res.json({items:q.rows})});
 app.post('/api/v1/crm/deals',async(req,res)=>{const u=await user(req,res);if(!u)return;const title=str(req.body?.title);if(!title)return res.status(400).json({error:'title_required'});let pipelineId=str(req.body?.pipeline_id),stageId=str(req.body?.stage_id);if(!pipelineId){pipelineId=(await pool.query('select id from crm_pipelines where is_default=true limit 1')).rows[0]?.id}if(!stageId&&pipelineId){stageId=(await pool.query("select id from crm_pipeline_stages where pipeline_id=$1 and stage_type='open' order by position limit 1",[pipelineId])).rows[0]?.id}if(!pipelineId||!stageId)return res.status(400).json({error:'pipeline_not_configured'});const stage=(await pool.query('select probability from crm_pipeline_stages where id=$1',[stageId])).rows[0];const q=await pool.query(`insert into crm_deals(title,customer_id,company_id,pipeline_id,stage_id,owner_id,amount,currency,probability,expected_close_at,source) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning *`,[title,str(req.body?.customer_id)||null,str(req.body?.company_id)||null,pipelineId,stageId,str(req.body?.owner_id)||u.id,Number(req.body?.amount)||0,str(req.body?.currency)||'IDR',Number(req.body?.probability??stage?.probability??0),req.body?.expected_close_at||null,str(req.body?.source)||null]);await audit('deal',q.rows[0].id,'created',u.id);if(q.rows[0].customer_id)await recomputeCustomerScore(q.rows[0].customer_id);res.status(201).json(q.rows[0])});
 app.post('/api/v1/crm/deals/:id/move',async(req,res)=>{const u=await user(req,res);if(!u)return;const stageId=str(req.body?.stage_id);const stage=(await pool.query('select * from crm_pipeline_stages where id=$1',[stageId])).rows[0];if(!stage)return res.status(400).json({error:'stage_not_found'});const status=stage.stage_type==='won'?'won':stage.stage_type==='lost'?'lost':'open';const q=await pool.query(`update crm_deals set stage_id=$2,probability=$3,status=$4,closed_at=case when $4 in('won','lost') then now() else null end,loss_reason=case when $4='lost' then $5 else null end,updated_at=now() where id=$1 returning *`,[req.params.id,stageId,stage.probability,status,str(req.body?.loss_reason)||null]);if(!q.rows[0])return res.status(404).json({error:'deal_not_found'});await audit('deal',req.params.id,'stage_changed',u.id,{stage_id:stageId,status});if(q.rows[0].customer_id)await recomputeCustomerScore(q.rows[0].customer_id);res.json(q.rows[0])});

 app.post('/api/v1/crm/activities',async(req,res)=>{const u=await user(req,res);if(!u)return;const type=str(req.body?.activity_type);if(!type)return res.status(400).json({error:'activity_type_required'});const q=await pool.query(`insert into crm_activities(customer_id,company_id,deal_id,conversation_id,operator_id,activity_type,subject,body,channel,status,due_at,completed_at,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,case when $10='completed' then now() else null end,$12) returning *`,[str(req.body?.customer_id)||null,str(req.body?.company_id)||null,str(req.body?.deal_id)||null,str(req.body?.conversation_id)||null,u.id,type,str(req.body?.subject)||null,str(req.body?.body)||null,str(req.body?.channel)||null,str(req.body?.status)||'completed',req.body?.due_at||null,JSON.stringify(req.body?.metadata||{})]);if(q.rows[0].customer_id){await pool.query('update customers set last_contact_at=now(),updated_at=now() where id=$1',[q.rows[0].customer_id]);await recomputeCustomerScore(q.rows[0].customer_id)}res.status(201).json(q.rows[0])});
 app.post('/api/v1/crm/tasks',async(req,res)=>{const u=await user(req,res);if(!u)return;const title=str(req.body?.title);if(!title)return res.status(400).json({error:'title_required'});const q=await pool.query(`insert into crm_tasks(title,description,customer_id,deal_id,assigned_to,created_by,priority,due_at) values($1,$2,$3,$4,$5,$6,$7,$8) returning *`,[title,str(req.body?.description)||null,str(req.body?.customer_id)||null,str(req.body?.deal_id)||null,str(req.body?.assigned_to)||u.id,u.id,str(req.body?.priority)||'normal',req.body?.due_at||null]);res.status(201).json(q.rows[0])});
 app.post('/api/v1/crm/tasks/:id/status',async(req,res)=>{const u=await user(req,res);if(!u)return;const status=str(req.body?.status);if(!['open','in_progress','done','cancelled'].includes(status))return res.status(400).json({error:'invalid_status'});const q=await pool.query(`update crm_tasks set status=$2,completed_at=case when $2='done' then now() else null end,updated_at=now() where id=$1 returning *`,[req.params.id,status]);res.json(q.rows[0])});

 app.post('/api/v1/crm/signals',async(req,res)=>{const u=await user(req,res);if(!u)return;if(!['admin','supervisor'].includes(u.role))return res.status(403).json({error:'forbidden'});const title=str(req.body?.title),type=str(req.body?.signal_type);if(!title||!type)return res.status(400).json({error:'title_and_signal_type_required'});const q=await pool.query(`insert into crm_ai_signals(customer_id,deal_id,signal_type,severity,score_delta,title,explanation,evidence,expires_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9) returning *`,[str(req.body?.customer_id)||null,str(req.body?.deal_id)||null,type,str(req.body?.severity)||'info',Number(req.body?.score_delta)||0,title,str(req.body?.explanation)||null,JSON.stringify(req.body?.evidence||{}),req.body?.expires_at||null]);if(q.rows[0].customer_id)await recomputeCustomerScore(q.rows[0].customer_id);res.status(201).json(q.rows[0])});
 app.get('/api/v1/crm/insights',async(req,res)=>{const u=await user(req,res);if(!u)return;const [hot,stale,risky,followups]=await Promise.all([pool.query("select id,name,phone,lead_score,lead_temperature,next_action_at from customers where lead_temperature='hot' order by lead_score desc limit 25"),pool.query("select id,name,phone,lead_score,last_contact_at from customers where coalesce(last_contact_at,created_at)<now()-interval '14 days' and lifecycle_stage not in('customer','lost') order by lead_score desc limit 25"),pool.query("select id,title,amount,ai_health,ai_risk_score,expected_close_at from crm_deals where status='open' and (ai_risk_score>=50 or expected_close_at<current_date) order by ai_risk_score desc limit 25"),pool.query("select id,name,phone,next_action_at from customers where next_action_at is not null and next_action_at<now()+interval '24 hours' order by next_action_at limit 25")]);res.json({hot_leads:hot.rows,stale_leads:stale.rows,risky_deals:risky.rows,followups:followups.rows})});
}
