import type {Express,Request,Response} from 'express';
import multer from 'multer';
import mammoth from 'mammoth';
import pdfParse from 'pdf-parse';
import {pool} from './db.js';

type User={id:string;name:string;role:string};
type Deps={requireUser:(req:Request,res:Response)=>Promise<User|null>};
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:15*1024*1024}});
function cleanText(s:string){return String(s||'').replace(/\r/g,'').replace(/[ \t]+/g,' ').replace(/\n{3,}/g,'\n\n').trim()}
function chunks(text:string,max=1400,overlap=180){const t=cleanText(text),out:string[]=[];let i=0;while(i<t.length){let end=Math.min(t.length,i+max);if(end<t.length){const cut=t.lastIndexOf('\n',end);if(cut>i+max*.55)end=cut}out.push(t.slice(i,end).trim());if(end>=t.length)break;i=Math.max(i+1,end-overlap)}return out.filter(Boolean)}
function cosine(a:number[],b:number[]){let dot=0,aa=0,bb=0;const n=Math.min(a.length,b.length);for(let i=0;i<n;i++){dot+=a[i]*b[i];aa+=a[i]*a[i];bb+=b[i]*b[i]}return aa&&bb?dot/(Math.sqrt(aa)*Math.sqrt(bb)):0}
async function embed(input:string|string[]){const key=process.env.OPENAI_API_KEY;if(!key)return null;const r=await fetch('https://api.openai.com/v1/embeddings',{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${key}`},body:JSON.stringify({model:process.env.OPENAI_EMBEDDING_MODEL||'text-embedding-3-small',input})});if(!r.ok)throw new Error(`embedding_provider_${r.status}`);const d:any=await r.json();return d.data.map((x:any)=>x.embedding as number[])}
async function extract(file:Express.Multer.File){const name=file.originalname.toLowerCase();if(file.mimetype==='application/pdf'||name.endsWith('.pdf'))return cleanText((await pdfParse(file.buffer)).text);if(file.mimetype==='application/vnd.openxmlformats-officedocument.wordprocessingml.document'||name.endsWith('.docx'))return cleanText((await mammoth.extractRawText({buffer:file.buffer})).value);if(file.mimetype.startsWith('text/')||/\.(txt|md|csv|json)$/i.test(name))return cleanText(file.buffer.toString('utf8'));throw new Error('unsupported_file_type')}
function lexicalScore(query:string,text:string){const q=[...new Set(query.toLowerCase().split(/[^a-z0-9]+/).filter(x=>x.length>2))];const h=text.toLowerCase();return q.reduce((n,w)=>n+(h.includes(w)?1:0),0)/(q.length||1)}

export async function migrateHybridRag(){await pool.query(`
 create table if not exists knowledge_documents(
  id uuid primary key default gen_random_uuid(),filename text not null,mime_type text,source_type text not null default 'upload',status text not null default 'uploaded',text_content text,byte_size int,uploaded_by uuid references operators(id),created_at timestamptz not null default now(),processed_at timestamptz,error text
 );
 create table if not exists agent_runtime_logs(
  id uuid primary key default gen_random_uuid(),conversation_id uuid references conversations(id) on delete set null,operator_id uuid references operators(id),agent_id uuid references ai_agents(id),query text not null,response_text text,knowledge_item_ids uuid[] not null default '{}',knowledge_versions jsonb not null default '[]',confidence text not null default 'low',provider text not null default 'fallback',created_at timestamptz not null default now()
 );
 create table if not exists knowledge_chunks(
  id uuid primary key default gen_random_uuid(),document_id uuid references knowledge_documents(id) on delete cascade,knowledge_item_id uuid references knowledge_items(id) on delete cascade,chunk_no int not null,content text not null,embedding double precision[],embedding_model text,metadata jsonb not null default '{}',created_at timestamptz not null default now()
 );
 create index if not exists idx_knowledge_chunks_document on knowledge_chunks(document_id,chunk_no);
 create index if not exists idx_knowledge_chunks_item on knowledge_chunks(knowledge_item_id,chunk_no);
 create table if not exists live_data_sources(
  id uuid primary key default gen_random_uuid(),slug text not null unique,name text not null,source_type text not null default 'internal',status text not null default 'disabled',description text,config jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now()
 );
 create table if not exists agent_tool_scopes(
  agent_id uuid not null references ai_agents(id) on delete cascade,data_source_id uuid not null references live_data_sources(id) on delete cascade,created_at timestamptz not null default now(),primary key(agent_id,data_source_id)
 );
 insert into live_data_sources(slug,name,description) values
 ('product-catalog','Product Catalog','Structured product facts, SKU and specifications'),('inventory','Inventory','Real-time stock availability'),('pricing','Pricing','Current price and promotion facts'),('orders','Orders','Order and shipment status'),('payments','Payments','Invoice and payment status') on conflict(slug) do nothing;
`)}

export async function hybridRetrieve(query:string,agentSlug:string,limit=8){const ag=(await pool.query("select id,name,department from ai_agents where slug=$1 and status='active'",[agentSlug])).rows[0];if(!ag)return{agent:null,items:[],mode:'none'};const rows=(await pool.query(`select kc.id chunk_id,kc.content,kc.embedding,kc.embedding_model,ki.id item_id,ki.title,ki.category,ki.authority_level,kv.version_no,kv.source_ref from knowledge_agent_scopes kas join knowledge_items ki on ki.id=kas.item_id join knowledge_versions kv on kv.id=ki.current_version_id join knowledge_chunks kc on kc.knowledge_item_id=ki.id where kas.agent_id=$1 and ki.status='published' and kv.status='published' and (kv.effective_from is null or kv.effective_from<=now()) and (kv.expires_at is null or kv.expires_at>now())`,[ag.id])).rows;const qEmb=(await embed(query))?.[0]||null;const scored=rows.map((r:any)=>{const lex=lexicalScore(query,`${r.title} ${r.content}`),sem=qEmb&&Array.isArray(r.embedding)?cosine(qEmb,r.embedding):0,authority=(7-Number(r.authority_level||6))/6,score=qEmb?sem*.62+lex*.23+authority*.15:lex*.72+authority*.28;return{...r,lexical_score:lex,semantic_score:sem,score}}).sort((a:any,b:any)=>b.score-a.score).slice(0,Math.max(1,Math.min(limit,12)));return{agent:ag,items:scored,mode:qEmb?'hybrid':'lexical',embedding_available:Boolean(qEmb)}}

export function registerHybridRagRoutes(app:Express,deps:Deps){
 app.post('/api/v1/rag/documents/upload',upload.single('file'),async(req,res)=>{const u=await deps.requireUser(req,res);if(!u)return;if(!['admin','supervisor'].includes(u.role))return res.status(403).json({error:'forbidden'});if(!req.file)return res.status(400).json({error:'file_required'});try{const text=await extract(req.file);if(!text)return res.status(400).json({error:'no_text_extracted'});const d=(await pool.query(`insert into knowledge_documents(filename,mime_type,source_type,status,text_content,byte_size,uploaded_by,processed_at) values($1,$2,'upload','parsed',$3,$4,$5,now()) returning *`,[req.file.originalname,req.file.mimetype,text,req.file.size,u.id])).rows[0];const item=(await pool.query(`insert into knowledge_items(title,category,source_type,authority_level,data_class,status,created_by) values($1,'Document','upload',3,'static','draft',$2) returning *`,[req.file.originalname,u.id])).rows[0];const ver=(await pool.query(`insert into knowledge_versions(item_id,version_no,content,summary,source_ref,status,created_by) values($1,1,$2,$3,$4,'draft',$5) returning *`,[item.id,text,text.slice(0,240),`document:${d.id}`,u.id])).rows[0];await pool.query('update knowledge_items set current_version_id=$2 where id=$1',[item.id,ver.id]);const cs=chunks(text);let embeddings:null|number[][]=null;try{embeddings=await embed(cs)}catch(e:any){await pool.query('update knowledge_documents set error=$2 where id=$1',[d.id,e.message])}for(let i=0;i<cs.length;i++)await pool.query('insert into knowledge_chunks(document_id,knowledge_item_id,chunk_no,content,embedding,embedding_model) values($1,$2,$3,$4,$5,$6)',[d.id,item.id,i,cs[i],embeddings?.[i]||null,embeddings?process.env.OPENAI_EMBEDDING_MODEL||'text-embedding-3-small':null]);res.status(201).json({ok:true,document:d,knowledge_item:item,chunks:cs.length,embedded:Boolean(embeddings)})}catch(e:any){res.status(400).json({error:e.message||'parse_failed'})}});
 app.post('/api/v1/rag/reindex/:itemId',async(req,res)=>{const u=await deps.requireUser(req,res);if(!u)return;if(u.role!=='admin')return res.status(403).json({error:'admin_required'});const q=(await pool.query(`select ki.id,kv.content from knowledge_items ki join knowledge_versions kv on kv.id=ki.current_version_id where ki.id=$1`,[req.params.itemId])).rows[0];if(!q)return res.status(404).json({error:'knowledge_not_found'});const cs=chunks(q.content);let embeddings:null|number[][]=null;try{embeddings=await embed(cs)}catch{}await pool.query('delete from knowledge_chunks where knowledge_item_id=$1',[q.id]);for(let i=0;i<cs.length;i++)await pool.query('insert into knowledge_chunks(knowledge_item_id,chunk_no,content,embedding,embedding_model) values($1,$2,$3,$4,$5)',[q.id,i,cs[i],embeddings?.[i]||null,embeddings?process.env.OPENAI_EMBEDDING_MODEL||'text-embedding-3-small':null]);res.json({ok:true,chunks:cs.length,embedded:Boolean(embeddings)})});
 app.post('/api/v1/rag/search',async(req,res)=>{const u=await deps.requireUser(req,res);if(!u)return;const query=String(req.body?.query||'').trim(),agent=String(req.body?.agent_slug||'supervisor-agent');if(!query)return res.status(400).json({error:'query_required'});res.json(await hybridRetrieve(query,agent,Number(req.body?.limit)||8))});
 app.get('/api/v1/tools/sources',async(req,res)=>{const u=await deps.requireUser(req,res);if(!u)return;const q=await pool.query('select id,slug,name,source_type,status,description,updated_at from live_data_sources order by name');res.json({items:q.rows})});
 app.post('/api/v1/tools/sources/:id/status',async(req,res)=>{const u=await deps.requireUser(req,res);if(!u)return;if(u.role!=='admin')return res.status(403).json({error:'admin_required'});const status=String(req.body?.status||'');if(!['disabled','testing','active'].includes(status))return res.status(400).json({error:'invalid_status'});const q=await pool.query('update live_data_sources set status=$2,updated_at=now() where id=$1 returning *',[req.params.id,status]);res.json(q.rows[0])});
 app.post('/api/v1/agent/grounded-preview/:conversationId',async(req,res)=>{const u=await deps.requireUser(req,res);if(!u)return;const draft=String(req.body?.operator_text||'').trim();if(!draft)return res.status(400).json({error:'operator_text_required'});const cv=(await pool.query(`select cv.id,cv.intent,c.name customer_name,(select original_text from messages where conversation_id=cv.id and direction='inbound' order by created_at desc limit 1) customer_text from conversations cv join customers c on c.id=cv.customer_id where cv.id=$1`,[req.params.conversationId])).rows[0];if(!cv)return res.status(404).json({error:'conversation_not_found'});const slug=['pricing','product_availability','sales','promotion'].includes(cv.intent)?'sales-agent':['payment','invoice','settlement'].includes(cv.intent)?'payment-agent':['support','refund','return','complaint'].includes(cv.intent)?'customer-service-agent':'supervisor-agent';const rag=await hybridRetrieve(`${cv.customer_text||''} ${draft}`,slug,6);const evidence=rag.items.map((x:any,i:number)=>`[K${i+1}] ${x.title} v${x.version_no}: ${x.content}`).join('\n\n');let reply=draft,provider='fallback';if(process.env.OPENAI_API_KEY){const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${process.env.OPENAI_API_KEY}`},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',input:`Rewrite the operator draft for WhatsApp. Use only facts in the operator draft and approved evidence. Never invent price, stock, ETA, discount, policy, payment status, or promises. If live facts are needed and no active tool source is available, state that verification is needed. Customer: ${cv.customer_name||'Customer'}\nMessage: ${cv.customer_text||''}\nDraft: ${draft}\nEvidence:\n${evidence||'(none)'}`,max_output_tokens:260})});if(r.ok){const d:any=await r.json();reply=String(d.output_text||draft).trim();provider='openai'}}await pool.query(`insert into agent_runtime_logs(conversation_id,operator_id,agent_id,query,response_text,knowledge_item_ids,knowledge_versions,confidence,provider) values($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[cv.id,u.id,rag.agent?.id||null,cv.customer_text||draft,reply,rag.items.map((x:any)=>x.item_id),JSON.stringify(rag.items.map((x:any)=>({item_id:x.item_id,version:x.version_no,score:x.score}))),rag.items.length>=2?'high':rag.items.length===1?'medium':'low',provider]);res.json({reply,agent_slug:slug,retrieval_mode:rag.mode,confidence:rag.items.length>=2?'high':rag.items.length===1?'medium':'low',evidence:rag.items.map((x:any)=>({title:x.title,version:x.version_no,authority:x.authority_level,score:Number(x.score.toFixed(3)),source_ref:x.source_ref}))})});
}
