import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
import { z } from 'zod';
import { pool,migrate,normalizePhone,chooseStickySender,slaIntervals } from './db.js';
import { classifyIntent,rewriteForCustomer } from './ai.js';

const app=express();
const port=Number(process.env.PORT||3000);
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(__dirname,'..');
app.use(express.json({limit:'10mb'}));

const ImportRow=z.object({phone:z.any(),name:z.string().optional(),source:z.string().optional(),tags:z.any().optional(),opt_in:z.any().optional(),opt_in_source:z.string().optional()});
const Account=z.object({name:z.string().min(2),phone:z.string(),phone_number_id:z.string().optional(),waba_id:z.string().optional(),department:z.string().optional(),mode:z.enum(['manual','assist','hybrid','auto']).default('hybrid')});
const OperatorInput=z.object({name:z.string().min(2),email:z.string().email().optional(),role:z.enum(['admin','supervisor','operator']).default('operator'),department:z.string().optional(),max_conversations:z.number().int().min(1).max(500).default(20)});
function dbReady(res:express.Response){if(!process.env.DATABASE_URL){res.status(503).json({error:'database_not_configured'});return false}return true}
function bool(v:any){return v===true||['true','yes','1','y'].includes(String(v).toLowerCase())}
function metaReady(){return Boolean(process.env.META_ACCESS_TOKEN&&process.env.META_GRAPH_VERSION)}
async function event(conversationId:string,type:string,actor:string,payload:any={}){await pool.query('insert into conversation_events(conversation_id,event_type,actor,payload) values($1,$2,$3,$4)',[conversationId,type,actor,JSON.stringify(payload)])}

async function resolveActor(req:express.Request){
  const id=String(req.header('x-relayos-operator-id')||'').trim();
  if(id){const q=await pool.query('select * from operators where id=$1 and active=true',[id]);if(q.rows[0])return{...q.rows[0],legacy:false};}
  const q=await pool.query("select * from operators where role='admin' and active=true order by created_at limit 1");
  return q.rows[0]?{...q.rows[0],legacy:true}:null;
}
function can(role:string,action:string){
  const matrix:any={admin:['*'],supervisor:['view','assign','transfer','escalate','close','note','reply','presence','queue','operator_presence'],operator:['view','note','reply','presence','claim','read']};
  return matrix[role]?.includes('*')||matrix[role]?.includes(action);
}
async function authorize(req:express.Request,res:express.Response,action:string){const actor=await resolveActor(req);if(!actor)return res.status(401).json({error:'operator_identity_required'});if(!can(actor.role,action))return res.status(403).json({error:'forbidden',role:actor.role,action});return actor;}
function dueDates(priority='normal'){const s=slaIntervals(priority);return{first:new Date(Date.now()+s.first*60000),resolution:new Date(Date.now()+s.resolution*60000)}}

app.get('/api/health',async(_req,res)=>{let database='not_configured';if(process.env.DATABASE_URL){try{await pool.query('select 1');database='connected'}catch{database='error'}}res.status(database==='error'?503:200).json({ok:database!=='error',service:'RelayOS',database,meta:metaReady()?'configured':'not_configured',timestamp:new Date().toISOString()})});

app.get('/api/v1/dashboard',async(_req,res)=>{if(!dbReady(res))return;const [customers,numbers,conversations,messages,unread,escalated,sla]=await Promise.all([
  pool.query('select count(*)::int total,count(*) filter(where opt_in)::int opted_in from customers'),
  pool.query("select count(*)::int total,count(*) filter(where health_score>=80 and status in('active','healthy','verified','verifying'))::int healthy from whatsapp_accounts"),
  pool.query("select count(*)::int open from conversations where status='open'"),
  pool.query("select count(*)::int total from messages where created_at>now()-interval '24 hours'"),
  pool.query('select coalesce(sum(unread_count),0)::int total from conversations'),
  pool.query("select count(*)::int total from conversations where escalation_status='escalated'"),
  pool.query("select count(*) filter(where status='open' and first_response_at is null and first_response_due_at<now())::int first_breached,count(*) filter(where status='open' and resolution_due_at<now())::int resolution_breached from conversations")
]);res.json({customers:customers.rows[0],numbers:numbers.rows[0],conversations:conversations.rows[0],messages24h:messages.rows[0].total,unread:unread.rows[0].total,escalated:escalated.rows[0].total,sla:sla.rows[0]})});

app.get('/api/v1/numbers',async(_req,res)=>{if(!dbReady(res))return;const q=await pool.query(`select wa.id,wa.name,wa.phone,wa.phone_number_id,wa.waba_id,wa.department,wa.mode,wa.health_score as health,wa.status,wa.last_webhook_at,wa.last_outbound_at,wa.last_error,count(c.id) filter(where c.status='open')::int as chats from whatsapp_accounts wa left join conversations c on c.whatsapp_account_id=wa.id group by wa.id order by wa.created_at`);res.json({items:q.rows})});
app.post('/api/v1/numbers',async(req,res)=>{if(!dbReady(res))return;const parsed=Account.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'invalid_account'});const p=normalizePhone(parsed.data.phone);if(!p)return res.status(400).json({error:'invalid_phone'});const d=parsed.data;const q=await pool.query(`insert into whatsapp_accounts(name,phone,phone_number_id,waba_id,department,mode,status) values($1,$2,$3,$4,$5,$6,'setup') on conflict(phone) do update set name=excluded.name,phone_number_id=coalesce(excluded.phone_number_id,whatsapp_accounts.phone_number_id),waba_id=coalesce(excluded.waba_id,whatsapp_accounts.waba_id),department=excluded.department,mode=excluded.mode,updated_at=now() returning *`,[d.name,p,d.phone_number_id||null,d.waba_id||null,d.department||null,d.mode]);res.status(201).json(q.rows[0])});
async function getMetaIdentity(phoneNumberId:string){if(!metaReady())throw new Error('meta_not_configured');const fields='display_phone_number,verified_name,quality_rating,platform_type';const r=await fetch(`https://graph.facebook.com/${process.env.META_GRAPH_VERSION}/${encodeURIComponent(phoneNumberId)}?fields=${encodeURIComponent(fields)}`,{headers:{authorization:`Bearer ${process.env.META_ACCESS_TOKEN}`}});const data:any=await r.json();if(!r.ok)throw new Error(data?.error?.message||`meta_http_${r.status}`);return data}
app.post('/api/v1/numbers/:id/verify',async(req,res)=>{if(!dbReady(res))return;const q=await pool.query('select * from whatsapp_accounts where id=$1',[req.params.id]);const a=q.rows[0];if(!a)return res.status(404).json({error:'account_not_found'});try{const identity=await getMetaIdentity(a.phone_number_id);await pool.query("update whatsapp_accounts set status='verified',health_score=greatest(health_score,80),last_error=null,updated_at=now() where id=$1",[a.id]);res.json({ok:true,...identity})}catch(e:any){await pool.query("update whatsapp_accounts set last_error=$2,updated_at=now() where id=$1",[a.id,e.message]);res.status(400).json({ok:false,error:e.message})}});
app.post('/api/v1/numbers/:id/activate',async(req,res)=>{if(!dbReady(res))return;const q=await pool.query('select * from whatsapp_accounts where id=$1',[req.params.id]);const a=q.rows[0];if(!a)return res.status(404).json({error:'account_not_found'});if(!a.phone_number_id||!a.waba_id)return res.status(400).json({error:'meta_identity_incomplete'});try{await getMetaIdentity(a.phone_number_id)}catch(e:any){return res.status(400).json({error:e.message})}const u=await pool.query("update whatsapp_accounts set status='active',health_score=100,last_error=null,updated_at=now() where id=$1 returning *",[a.id]);res.json({ok:true,account:u.rows[0]})});

app.get('/api/v1/customers',async(req,res)=>{if(!dbReady(res))return;const limit=Math.min(Number(req.query.limit)||100,500);const q=await pool.query(`select c.id,c.phone,c.name,c.source,c.tags,c.opt_in,c.opt_in_source,c.do_not_contact,c.created_at,wa.name assigned_sender from customers c left join whatsapp_accounts wa on wa.id=c.assigned_whatsapp_id order by c.updated_at desc limit $1`,[limit]);res.json({items:q.rows})});
app.post('/api/v1/customers/import',async(req,res)=>{if(!dbReady(res))return;const rows=Array.isArray(req.body?.rows)?req.body.rows:[];if(rows.length>10000)return res.status(413).json({error:'max_10000_rows_per_import'});let valid=0,invalid=0,inserted=0,updated=0;const seen=new Set<string>();const client=await pool.connect();try{await client.query('begin');for(const raw of rows){const parsed=ImportRow.safeParse(raw);if(!parsed.success){invalid++;continue}const phone=normalizePhone(String(parsed.data.phone));if(!phone){invalid++;continue}valid++;if(seen.has(phone))continue;seen.add(phone);const tags=Array.isArray(parsed.data.tags)?parsed.data.tags:String(parsed.data.tags||'').split(',').map(x=>x.trim()).filter(Boolean);const existing=await client.query('select id from customers where phone=$1',[phone]);await client.query(`insert into customers(phone,name,source,tags,opt_in,opt_in_source,opt_in_at) values($1,$2,$3,$4,$5,$6,case when $5 then now() else null end) on conflict(phone) do update set name=coalesce(excluded.name,customers.name),source=coalesce(excluded.source,customers.source),tags=case when cardinality(excluded.tags)>0 then excluded.tags else customers.tags end,opt_in=customers.opt_in or excluded.opt_in,opt_in_source=coalesce(excluded.opt_in_source,customers.opt_in_source),updated_at=now()`,[phone,parsed.data.name||null,parsed.data.source||null,tags,bool(parsed.data.opt_in),parsed.data.opt_in_source||null]);existing.rowCount?updated++:inserted++}await client.query('commit');res.json({total:rows.length,valid,invalid,duplicates_in_file:valid-seen.size,inserted,updated})}catch(e){await client.query('rollback');throw e}finally{client.release()}});

const convoSelect=`select cv.id,cv.status,cv.intent,cv.ai_mode,cv.assigned_operator,cv.assigned_operator_id,op.name assigned_operator_name,op.role assigned_operator_role,cv.unread_count,cv.priority,cv.escalation_status,cv.escalation_reason,cv.escalated_at,cv.closed_at,cv.first_response_due_at,cv.resolution_due_at,cv.first_response_at,cv.sla_breached_at,cv.last_message_at,c.id customer_id,c.name customer_name,c.phone customer_phone,c.opt_in,c.source,wa.id whatsapp_account_id,wa.name channel_name,wa.phone channel_phone,wa.status channel_status,wa.department,(select coalesce(m.rewritten_text,m.original_text) from messages m where m.conversation_id=cv.id order by m.created_at desc limit 1) last_message from conversations cv join customers c on c.id=cv.customer_id join whatsapp_accounts wa on wa.id=cv.whatsapp_account_id left join operators op on op.id=cv.assigned_operator_id`;
app.get('/api/v1/conversations',async(req,res)=>{if(!dbReady(res))return;const limit=Math.min(Number(req.query.limit)||100,300);await pool.query("update conversations set sla_breached_at=coalesce(sla_breached_at,now()) where status='open' and ((first_response_at is null and first_response_due_at<now()) or resolution_due_at<now()) and sla_breached_at is null");const q=await pool.query(`${convoSelect} order by case when cv.escalation_status='escalated' then 0 else 1 end,case when cv.sla_breached_at is not null then 0 else 1 end,cv.unread_count desc,cv.last_message_at desc limit $1`,[limit]);res.json({items:q.rows})});
app.get('/api/v1/conversations/:id/messages',async(req,res)=>{if(!dbReady(res))return;const [m,n,e]=await Promise.all([pool.query('select * from messages where conversation_id=$1 order by created_at',[req.params.id]),pool.query('select * from conversation_notes where conversation_id=$1 order by created_at desc',[req.params.id]),pool.query('select * from conversation_events where conversation_id=$1 order by created_at desc limit 50',[req.params.id])]);res.json({items:m.rows,notes:n.rows,events:e.rows})});
app.post('/api/v1/conversations/:id/read',async(req,res)=>{if(!dbReady(res))return;const actor=await authorize(req,res,'read');if(!actor)return;const q=await pool.query('update conversations set unread_count=0,last_read_at=now() where id=$1 returning *',[req.params.id]);if(!q.rowCount)return res.status(404).json({error:'conversation_not_found'});await event(req.params.id,'read',actor.name);res.json({ok:true})});
app.post('/api/v1/conversations/:id/assign',async(req,res)=>{if(!dbReady(res))return;const actor=await authorize(req,res,'assign');if(!actor)return;const operatorId=String(req.body?.operator_id||'').trim()||null;let op:any=null;if(operatorId){const oq=await pool.query('select * from operators where id=$1 and active=true',[operatorId]);op=oq.rows[0];if(!op)return res.status(400).json({error:'operator_not_found'});}const q=await pool.query('update conversations set assigned_operator_id=$2,assigned_operator=$3 where id=$1 returning *',[req.params.id,operatorId,op?.name||null]);if(!q.rowCount)return res.status(404).json({error:'conversation_not_found'});await event(req.params.id,'assigned',actor.name,{operator_id:operatorId,operator:op?.name||null});res.json({ok:true,conversation:q.rows[0]})});
app.post('/api/v1/conversations/:id/claim',async(req,res)=>{if(!dbReady(res))return;const actor=await authorize(req,res,'claim');if(!actor)return;const q=await pool.query('update conversations set assigned_operator_id=$2,assigned_operator=$3 where id=$1 and (assigned_operator_id is null or assigned_operator_id=$2) returning *',[req.params.id,actor.id,actor.name]);if(!q.rowCount)return res.status(409).json({error:'conversation_already_assigned'});await event(req.params.id,'claimed',actor.name,{operator_id:actor.id});res.json({ok:true,conversation:q.rows[0]})});
app.post('/api/v1/conversations/:id/status',async(req,res)=>{if(!dbReady(res))return;const actor=await authorize(req,res,'close');if(!actor)return;const status=String(req.body?.status||'');if(!['open','closed'].includes(status))return res.status(400).json({error:'invalid_status'});const q=await pool.query("update conversations set status=$2,closed_at=case when $2='closed' then now() else null end where id=$1 returning *",[req.params.id,status]);if(!q.rowCount)return res.status(404).json({error:'conversation_not_found'});await event(req.params.id,status==='closed'?'closed':'reopened',actor.name);res.json({ok:true,conversation:q.rows[0]})});
app.post('/api/v1/conversations/:id/note',async(req,res)=>{if(!dbReady(res))return;const actor=await authorize(req,res,'note');if(!actor)return;const body=String(req.body?.body||'').trim();if(!body)return res.status(400).json({error:'note_required'});const q=await pool.query('insert into conversation_notes(conversation_id,author,body) values($1,$2,$3) returning *',[req.params.id,actor.name,body]);await event(req.params.id,'note_added',actor.name);res.status(201).json(q.rows[0])});
app.post('/api/v1/conversations/:id/escalate',async(req,res)=>{if(!dbReady(res))return;const actor=await authorize(req,res,'escalate');if(!actor)return;const escalated=bool(req.body?.escalated??true);const reason=String(req.body?.reason||'').trim()||null;const q=await pool.query("update conversations set escalation_status=$2,escalation_reason=$3,escalated_at=case when $2='escalated' then now() else null end,priority=case when $2='escalated' then 'high' else 'normal' end where id=$1 returning *",[req.params.id,escalated?'escalated':'none',reason]);if(!q.rowCount)return res.status(404).json({error:'conversation_not_found'});await event(req.params.id,escalated?'escalated':'deescalated',actor.name,{reason});res.json({ok:true,conversation:q.rows[0]})});
app.post('/api/v1/conversations/:id/transfer',async(req,res)=>{if(!dbReady(res))return;const actor=await authorize(req,res,'transfer');if(!actor)return;const senderId=String(req.body?.whatsapp_account_id||'');if(!senderId)return res.status(400).json({error:'whatsapp_account_id_required'});const old=await pool.query(`${convoSelect} where cv.id=$1`,[req.params.id]);if(!old.rowCount)return res.status(404).json({error:'conversation_not_found'});const cv=old.rows[0];const client=await pool.connect();try{await client.query('begin');await client.query("update conversations set status='closed',closed_at=now() where id=$1",[cv.id]);const due=dueDates(cv.priority);const n=await client.query("insert into conversations(customer_id,whatsapp_account_id,status,intent,ai_mode,assigned_operator,assigned_operator_id,priority,escalation_status,first_response_due_at,resolution_due_at,last_message_at) values($1,$2,'open',$3,$4,$5,$6,$7,$8,$9,$10,now()) returning *",[cv.customer_id,senderId,cv.intent,cv.ai_mode,cv.assigned_operator,cv.assigned_operator_id,cv.priority,cv.escalation_status,due.first,due.resolution]);await client.query('update customers set assigned_whatsapp_id=$1,updated_at=now() where id=$2',[senderId,cv.customer_id]);await client.query('insert into conversation_events(conversation_id,event_type,actor,payload) values($1,$2,$3,$4)',[cv.id,'transferred_out',actor.name,JSON.stringify({to:senderId,new_conversation_id:n.rows[0].id})]);await client.query('insert into conversation_events(conversation_id,event_type,actor,payload) values($1,$2,$3,$4)',[n.rows[0].id,'transferred_in',actor.name,JSON.stringify({from:cv.whatsapp_account_id,old_conversation_id:cv.id})]);await client.query('commit');res.json({ok:true,new_conversation_id:n.rows[0].id})}catch(e){await client.query('rollback');throw e}finally{client.release()}});

app.get('/api/v1/operators',async(_req,res)=>{if(!dbReady(res))return;const q=await pool.query(`select o.id,o.name,o.email,o.role,o.presence,o.department,o.max_conversations,o.active,o.last_seen_at,count(c.id) filter(where c.status='open')::int workload,count(c.id) filter(where c.status='open' and c.escalation_status='escalated')::int escalated from operators o left join conversations c on c.assigned_operator_id=o.id group by o.id order by case o.presence when 'online' then 0 when 'away' then 1 else 2 end,o.role,o.name`);res.json({items:q.rows})});
app.post('/api/v1/operators',async(req,res)=>{if(!dbReady(res))return;const actor=await authorize(req,res,'operator_presence');if(!actor||actor.role!=='admin')return actor?res.status(403).json({error:'admin_required'}):undefined;const p=OperatorInput.safeParse(req.body);if(!p.success)return res.status(400).json({error:'invalid_operator'});const d=p.data;const q=await pool.query(`insert into operators(name,email,role,department,max_conversations) values($1,$2,$3,$4,$5) returning *`,[d.name,d.email||null,d.role,d.department||null,d.max_conversations]);res.status(201).json(q.rows[0])});
app.patch('/api/v1/operators/:id',async(req,res)=>{if(!dbReady(res))return;const actor=await authorize(req,res,'operator_presence');if(!actor)return;const target=await pool.query('select * from operators where id=$1',[req.params.id]);if(!target.rows[0])return res.status(404).json({error:'operator_not_found'});if(actor.role!=='admin'&&req.body?.role&&req.body.role!==target.rows[0].role)return res.status(403).json({error:'admin_required_for_role_change'});const q=await pool.query(`update operators set name=coalesce($2,name),email=coalesce($3,email),role=coalesce($4,role),department=coalesce($5,department),max_conversations=coalesce($6,max_conversations),active=coalesce($7,active),updated_at=now() where id=$1 returning *`,[req.params.id,req.body?.name||null,req.body?.email||null,req.body?.role||null,req.body?.department||null,req.body?.max_conversations??null,req.body?.active??null]);res.json(q.rows[0])});
app.post('/api/v1/operators/:id/presence',async(req,res)=>{if(!dbReady(res))return;const actor=await resolveActor(req);if(!actor)return res.status(401).json({error:'operator_identity_required'});if(actor.id!==req.params.id&&!can(actor.role,'operator_presence'))return res.status(403).json({error:'forbidden'});const presence=String(req.body?.presence||'');if(!['online','away','offline'].includes(presence))return res.status(400).json({error:'invalid_presence'});const q=await pool.query('update operators set presence=$2,last_seen_at=now(),updated_at=now() where id=$1 returning *',[req.params.id,presence]);res.json(q.rows[0])});
app.get('/api/v1/assignment-queue',async(req,res)=>{if(!dbReady(res))return;const actor=await authorize(req,res,'view');if(!actor)return;const q=await pool.query(`${convoSelect} where cv.status='open' and cv.assigned_operator_id is null order by case when cv.escalation_status='escalated' then 0 else 1 end,case when cv.sla_breached_at is not null then 0 else 1 end,cv.first_response_due_at asc nulls last,cv.last_message_at asc limit 100`);res.json({items:q.rows})});
app.post('/api/v1/assignment-queue/assign-next',async(req,res)=>{if(!dbReady(res))return;const actor=await authorize(req,res,'queue');if(!actor)return;const department=String(req.body?.department||'').trim()||null;const client=await pool.connect();try{await client.query('begin');const cq=await client.query(`select cv.id,wa.department from conversations cv join whatsapp_accounts wa on wa.id=cv.whatsapp_account_id where cv.status='open' and cv.assigned_operator_id is null and ($1::text is null or wa.department=$1) order by case when cv.escalation_status='escalated' then 0 else 1 end,case when cv.sla_breached_at is not null then 0 else 1 end,cv.first_response_due_at asc nulls last,cv.last_message_at asc for update skip locked limit 1`,[department]);if(!cq.rows[0]){await client.query('rollback');return res.status(404).json({error:'queue_empty'});}const opq=await client.query(`select o.id,o.name,o.max_conversations,count(c.id) filter(where c.status='open')::int workload from operators o left join conversations c on c.assigned_operator_id=o.id where o.active=true and o.presence='online' and o.role in('operator','supervisor') and ($1::text is null or o.department=$1 or o.department is null) group by o.id having count(c.id) filter(where c.status='open') < o.max_conversations order by count(c.id) filter(where c.status='open'),o.last_seen_at desc nulls last limit 1`,[department||cq.rows[0].department]);if(!opq.rows[0]){await client.query('rollback');return res.status(409).json({error:'no_available_operator'});}await client.query('update conversations set assigned_operator_id=$2,assigned_operator=$3 where id=$1',[cq.rows[0].id,opq.rows[0].id,opq.rows[0].name]);await client.query('insert into conversation_events(conversation_id,event_type,actor,payload) values($1,$2,$3,$4)',[cq.rows[0].id,'auto_assigned',actor.name,JSON.stringify({operator_id:opq.rows[0].id,operator:opq.rows[0].name})]);await client.query('commit');res.json({ok:true,conversation_id:cq.rows[0].id,operator:opq.rows[0]})}catch(e){await client.query('rollback');throw e}finally{client.release()}});
app.get('/api/v1/sla/summary',async(_req,res)=>{if(!dbReady(res))return;const q=await pool.query(`select count(*) filter(where status='open')::int open,count(*) filter(where status='open' and first_response_at is null and first_response_due_at<now())::int first_response_breached,count(*) filter(where status='open' and resolution_due_at<now())::int resolution_breached,count(*) filter(where status='open' and first_response_at is null and first_response_due_at between now() and now()+interval '15 minutes')::int first_response_at_risk from conversations`);res.json(q.rows[0])});

app.post('/api/v1/conversations/:id/operator-preview',async(req,res)=>{if(!dbReady(res))return;const actor=await authorize(req,res,'reply');if(!actor)return;const text=String(req.body?.text||'').trim();if(!text)return res.status(400).json({error:'text_required'});const q=await pool.query(`${convoSelect} where cv.id=$1`,[req.params.id]);const cv=q.rows[0];if(!cv)return res.status(404).json({error:'conversation_not_found'});if(actor.role==='operator'&&cv.assigned_operator_id&&cv.assigned_operator_id!==actor.id)return res.status(403).json({error:'conversation_assigned_to_another_operator'});const last=await pool.query("select original_text from messages where conversation_id=$1 and direction='inbound' order by created_at desc limit 1",[cv.id]);const rewritten=await rewriteForCustomer({customerName:cv.customer_name,intent:cv.intent,operatorText:text,customerText:last.rows[0]?.original_text});res.json({original_text:text,rewritten_text:rewritten,ai_available:Boolean(process.env.OPENAI_API_KEY)})});
async function sendWhatsApp(phoneNumberId:string,to:string,text:string){if(!process.env.META_ACCESS_TOKEN||!process.env.META_GRAPH_VERSION)return{queued:false,reason:'meta_not_configured'};const r=await fetch(`https://graph.facebook.com/${process.env.META_GRAPH_VERSION}/${phoneNumberId}/messages`,{method:'POST',headers:{authorization:`Bearer ${process.env.META_ACCESS_TOKEN}`,'content-type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to,type:'text',text:{body:text,preview_url:false}})});const data:any=await r.json();if(!r.ok)throw new Error(`Meta send failed ${r.status}: ${JSON.stringify(data).slice(0,300)}`);return{queued:true,data}}
app.post('/api/v1/conversations/:id/operator-send',async(req,res)=>{if(!dbReady(res))return;const actor=await authorize(req,res,'reply');if(!actor)return;const original=String(req.body?.original_text||'').trim();const rewritten=String(req.body?.rewritten_text||original).trim();if(!rewritten)return res.status(400).json({error:'text_required'});const q=await pool.query(`${convoSelect} where cv.id=$1`,[req.params.id]);const cv=q.rows[0];if(!cv)return res.status(404).json({error:'conversation_not_found'});if(actor.role==='operator'&&cv.assigned_operator_id&&cv.assigned_operator_id!==actor.id)return res.status(403).json({error:'conversation_assigned_to_another_operator'});const m=await pool.query(`insert into messages(conversation_id,direction,sender_type,original_text,rewritten_text,delivery_status) values($1,'outbound','operator',$2,$3,'queued') returning *`,[cv.id,original||rewritten,rewritten]);let delivery:any={queued:false,reason:'phone_number_id_missing'};try{if(cv.channel_phone&&cv.whatsapp_account_id){const wa=await pool.query('select phone_number_id from whatsapp_accounts where id=$1',[cv.whatsapp_account_id]);if(wa.rows[0]?.phone_number_id)delivery=await sendWhatsApp(wa.rows[0].phone_number_id,cv.customer_phone,rewritten)}}catch(e:any){delivery={queued:false,reason:e.message};await pool.query('update whatsapp_accounts set health_score=greatest(0,health_score-10),last_error=$2 where id=$1',[cv.whatsapp_account_id,e.message])}const externalId=delivery?.data?.messages?.[0]?.id||null;await pool.query(`update messages set external_message_id=coalesce($1,external_message_id),delivery_status=$2,sent_at=case when $2='sent' then now() else sent_at end,metadata=$3 where id=$4`,[externalId,delivery.queued?'sent':'draft',JSON.stringify(delivery),m.rows[0].id]);await pool.query(`update conversations set last_message_at=now(),first_response_at=coalesce(first_response_at,now()),assigned_operator_id=coalesce(assigned_operator_id,$2),assigned_operator=coalesce(assigned_operator,$3) where id=$1`,[cv.id,actor.id,actor.name]);if(delivery.queued)await pool.query('update whatsapp_accounts set last_outbound_at=now(),last_error=null where id=$1',[cv.whatsapp_account_id]);await event(cv.id,'operator_reply',actor.name,{delivery:delivery.queued?'sent':'draft'});res.json({message:{...m.rows[0],external_message_id:externalId,rewritten_text:rewritten},delivery})});

app.get('/api/webhooks/meta',async(req,res)=>{const mode=req.query['hub.mode'],token=req.query['hub.verify_token'],challenge=req.query['hub.challenge'];if(mode==='subscribe'&&token===process.env.META_VERIFY_TOKEN)return res.status(200).send(String(challenge||''));res.sendStatus(403)});
app.post('/api/webhooks/meta',async(req,res)=>{res.sendStatus(200);if(!process.env.DATABASE_URL)return;try{const changes=req.body?.entry?.flatMap((e:any)=>e.changes||[])||[];for(const change of changes){const value=change.value||{};const phoneNumberId=value.metadata?.phone_number_id;if(phoneNumberId)await pool.query('update whatsapp_accounts set last_webhook_at=now(),last_error=null where phone_number_id=$1',[phoneNumberId]);for(const st of value.statuses||[]){const status=String(st.status||'');const col:any={sent:'sent_at',delivered:'delivered_at',read:'read_at',failed:'failed_at'}[status];if(['sent','delivered','read','failed'].includes(status)){await pool.query(`update messages set delivery_status=$2,${col}=now(),metadata=metadata||$3::jsonb where external_message_id=$1`,[st.id,status,JSON.stringify({meta_status:st})]);if(status==='failed'&&phoneNumberId)await pool.query('update whatsapp_accounts set health_score=greatest(0,health_score-8),last_error=$2 where phone_number_id=$1',[phoneNumberId,JSON.stringify(st.errors||[]).slice(0,500)])}}
for(const msg of value.messages||[]){const eventKey=`meta:${msg.id}`;const inserted=await pool.query('insert into inbound_events(provider,event_key,payload) values($1,$2,$3) on conflict(event_key) do nothing returning id',['meta',eventKey,JSON.stringify(msg)]);if(!inserted.rowCount)continue;const phone=normalizePhone(msg.from);const text=msg.text?.body||msg.button?.text||msg.interactive?.button_reply?.title||'';if(!phone)continue;const cq=await pool.query(`insert into customers(phone,source) values($1,'whatsapp') on conflict(phone) do update set updated_at=now() returning id,name,assigned_whatsapp_id`,[phone]);const customer=cq.rows[0];let senderId=customer.assigned_whatsapp_id;if(phoneNumberId){const wa=await pool.query('select id from whatsapp_accounts where phone_number_id=$1',[phoneNumberId]);if(wa.rows[0]){senderId=wa.rows[0].id;if(!customer.assigned_whatsapp_id)await pool.query('update customers set assigned_whatsapp_id=$1 where id=$2',[senderId,customer.id])}}if(!senderId)senderId=await chooseStickySender(customer.id);const open=await pool.query("select id from conversations where customer_id=$1 and whatsapp_account_id=$2 and status='open' order by created_at desc limit 1",[customer.id,senderId]);let conversationId=open.rows[0]?.id;const intent=await classifyIntent(text);if(!conversationId){const due=dueDates('normal');const n=await pool.query("insert into conversations(customer_id,whatsapp_account_id,intent,unread_count,first_response_due_at,resolution_due_at) values($1,$2,$3,1,$4,$5) returning id",[customer.id,senderId,intent,due.first,due.resolution]);conversationId=n.rows[0].id;await event(conversationId,'created','Meta',{intent})}else await pool.query('update conversations set unread_count=unread_count+1,last_message_at=now(),intent=coalesce($2,intent) where id=$1',[conversationId,intent]);await pool.query(`insert into messages(conversation_id,direction,sender_type,external_message_id,original_text,delivery_status,metadata) values($1,'inbound','customer',$2,$3,'received',$4)`,[conversationId,msg.id,text,JSON.stringify(msg)])}}
}catch(e){console.error('meta_webhook_error',e)}});

app.use(express.static(path.join(root,'dist')));
app.get('*',(_req,res)=>res.sendFile(path.join(root,'dist','index.html')));
migrate().then(()=>app.listen(port,()=>console.log(`RelayOS listening on ${port}`))).catch(e=>{console.error('migration_failed',e);process.exit(1)});
