import type {Express,Request,Response} from 'express';
import {pool,normalizePhone} from './db.js';

type User={id:string;name:string;role:string;department?:string};
type Deps={requireUser:(req:Request,res:Response)=>Promise<User|null>};
type MetaPhone={id:string;display_phone_number?:string;verified_name?:string;quality_rating?:string;code_verification_status?:string;platform_type?:string};
type Account={id:string;phone:string;waba_id?:string|null;status?:string;[key:string]:any};

function metaConfig(){return{token:String(process.env.META_ACCESS_TOKEN||'').trim(),version:String(process.env.META_GRAPH_VERSION||'').trim(),defaultWabaId:String(process.env.RELAYOS_PRIMARY_WABA_ID||'').trim(),primaryPhone:normalizePhone(process.env.RELAYOS_PRIMARY_PHONE||''),primaryPhoneNumberId:String(process.env.RELAYOS_PRIMARY_PHONE_NUMBER_ID||'').trim()}}
function externalOrigin(req:Request){const p=String(req.headers['x-forwarded-proto']||req.protocol).split(',')[0].trim(),h=String(req.headers['x-forwarded-host']||req.get('host')||'').split(',')[0].trim();return`${p}://${h}`}
function checkOrigin(req:Request,res:Response){const o=String(req.headers.origin||'');if(!o)return true;if(o!==externalOrigin(req)){res.status(403).json({error:'origin_rejected'});return false}return true}
async function requireAdmin(req:Request,res:Response,deps:Deps){const u=await deps.requireUser(req,res);if(!u)return null;if(u.role!=='admin'){res.status(403).json({error:'admin_required'});return null}return u}
async function listMetaPhones(wabaId:string){const{token,version}=metaConfig();if(!token||!version){const err:any=new Error('Meta access token or Graph version is not configured.');err.code='meta_credentials_not_configured';err.status=503;throw err}let url=`https://graph.facebook.com/${encodeURIComponent(version)}/${encodeURIComponent(wabaId)}/phone_numbers?fields=${encodeURIComponent('id,display_phone_number,verified_name,quality_rating,code_verification_status,platform_type')}&limit=100`;const out:MetaPhone[]=[];for(let page=0;page<5&&url;page++){const r=await fetch(url,{headers:{authorization:`Bearer ${token}`}});const data:any=await r.json().catch(()=>({}));if(!r.ok){const err:any=new Error(data?.error?.message||`Meta Graph API returned HTTP ${r.status}.`);err.code='meta_phone_discovery_failed';err.status=r.status>=500?502:400;throw err}if(Array.isArray(data?.data))out.push(...data.data);url=typeof data?.paging?.next==='string'?data.paging.next:''}return out}
function maskedPhones(phones:MetaPhone[]){return phones.map(p=>{const n=normalizePhone(p.display_phone_number||'');return n?`••••${n.slice(-4)}`:'unknown'})}
async function discoverAccount(account:Account,requestedWabaId?:string){const c=metaConfig(),accountPhone=normalizePhone(account.phone||'');if(!accountPhone){const err:any=new Error('The saved WhatsApp number is invalid.');err.code='invalid_account_phone';err.status=400;throw err}const wabaId=String(requestedWabaId||account.waba_id||c.defaultWabaId||'').trim();if(!wabaId){const err:any=new Error('Configure RELAYOS_PRIMARY_WABA_ID in Railway or provide a WABA ID for this account.');err.code='default_waba_not_configured';err.status=400;throw err}
  let match:MetaPhone|undefined,source:'railway_primary'|'meta_discovery';let phones:MetaPhone[]=[];
  if(c.primaryPhone&&c.primaryPhoneNumberId&&accountPhone===c.primaryPhone){match={id:c.primaryPhoneNumberId,display_phone_number:account.phone};source='railway_primary'}else{phones=await listMetaPhones(wabaId);match=phones.find(p=>normalizePhone(p.display_phone_number||'')===accountPhone);source='meta_discovery';if(!match){const err:any=new Error('This phone number is not registered under the configured WhatsApp Business Account.');err.code='phone_not_found_in_waba';err.status=404;err.extra={waba_id:wabaId,registered_count:phones.length,registered_numbers_masked:maskedPhones(phones)};throw err}}
  const updated=(await pool.query(`update whatsapp_accounts set phone_number_id=$2,waba_id=$3,status=case when status='setup' then 'verifying' else status end,last_error=null,updated_at=now() where id=$1 returning *`,[account.id,String(match.id),wabaId])).rows[0];
  return{account:updated,wabaId,match,source};
}
async function rememberFailure(accountId:string|undefined,e:any){if(!accountId)return;await pool.query('update whatsapp_accounts set last_error=$2,updated_at=now() where id=$1',[accountId,String(e?.message||'meta_discovery_failed')]).catch(()=>{})}
function sendDiscoveryError(res:Response,e:any,legacy=false){const code=String(e?.code||'meta_discovery_failed'),status=Number(e?.status)||400;const error=legacy&&code==='phone_not_found_in_waba'?'phone_not_found_in_configured_waba':code;return res.status(status).json({error,detail:String(e?.message||'Unable to discover Meta sender identity.'),...(e?.extra||{})})}

export function registerMetaOnboardingRoutes(app:Express,deps:Deps){
  app.get('/api/v1/meta-onboarding/config',async(req,res)=>{const u=await requireAdmin(req,res,deps);if(!u)return;const c=metaConfig();res.json({configured:Boolean(c.token&&c.version&&c.defaultWabaId),default_waba_configured:Boolean(c.defaultWabaId),primary_identity_configured:Boolean(c.primaryPhone&&c.primaryPhoneNumberId),graph_version:c.version||null})});

  app.post('/api/v1/numbers/:id/discover-meta',async(req,res)=>{if(!checkOrigin(req,res))return;const u=await requireAdmin(req,res,deps);if(!u)return;const account=(await pool.query('select * from whatsapp_accounts where id=$1',[req.params.id])).rows[0] as Account|undefined;if(!account)return res.status(404).json({error:'account_not_found'});try{const d=await discoverAccount(account,String(req.body?.waba_id||'').trim()||undefined);res.json({ok:true,source:d.source,account:d.account,meta:{id:d.match.id,display_phone_number:d.match.display_phone_number||account.phone,verified_name:d.match.verified_name||null,quality_rating:d.match.quality_rating||null,code_verification_status:d.match.code_verification_status||null,platform_type:d.match.platform_type||null}})}catch(e:any){await rememberFailure(account.id,e);sendDiscoveryError(res,e)}});

  // Backward-compatible endpoint used by the current onboarding UI. It now shares
  // the same hardened discovery path as /numbers/:id/discover-meta.
  app.post('/api/v1/meta/discover-number',async(req,res)=>{if(!checkOrigin(req,res))return;const u=await requireAdmin(req,res,deps);if(!u)return;const accountId=String(req.body?.account_id||'').trim();const phone=normalizePhone(req.body?.phone||'');if(!accountId&&!phone)return res.status(400).json({error:'invalid_phone'});const q=accountId?await pool.query('select * from whatsapp_accounts where id=$1',[accountId]):await pool.query('select * from whatsapp_accounts where phone=$1',[phone]);const account=q.rows[0] as Account|undefined;if(!account)return res.status(404).json({error:'account_not_found'});try{const d=await discoverAccount(account);res.json({ok:true,source:d.source==='railway_primary'?'railway_primary_config':'meta_waba_phone_numbers',phone_number_id:String(d.match.id),waba_id:d.wabaId,display_phone_number:d.match.display_phone_number||account.phone,verified_name:d.match.verified_name||null,quality_rating:d.match.quality_rating||null,code_verification_status:d.match.code_verification_status||null,platform_type:d.match.platform_type||null,account:d.account})}catch(e:any){await rememberFailure(account.id,e);sendDiscoveryError(res,e,true)}});

  app.patch('/api/v1/numbers/:id/meta-identity',async(req,res)=>{if(!checkOrigin(req,res))return;const u=await requireAdmin(req,res,deps);if(!u)return;const phoneNumberId=String(req.body?.phone_number_id||'').trim(),wabaId=String(req.body?.waba_id||metaConfig().defaultWabaId||'').trim();if(!phoneNumberId||!wabaId)return res.status(400).json({error:'phone_number_id_and_waba_id_required'});const q=await pool.query(`update whatsapp_accounts set phone_number_id=$2,waba_id=$3,status=case when status='setup' then 'verifying' else status end,last_error=null,updated_at=now() where id=$1 returning *`,[req.params.id,phoneNumberId,wabaId]);if(!q.rowCount)return res.status(404).json({error:'account_not_found'});res.json({ok:true,account:q.rows[0]})});
}
