import type {Express,Request,Response} from 'express';
import {pool} from './db.js';

type User={id:string;name:string;email?:string;role:string;department?:string};
type Deps={requireUser:(req:Request,res:Response)=>Promise<User|null>};

function arr(v:any){return Array.isArray(v)?v.map(String):String(v||'').split(',').map(x=>x.trim()).filter(Boolean)}
function words(v:string){return String(v||'').toLowerCase().replace(/[^a-z0-9\u00c0-\u024f\u1e00-\u1eff]+/g,' ').split(/\s+/).filter(x=>x.length>1)}
function agentForIntent(intent:string){
  if(['pricing','product_availability','sales','promotion'].includes(intent))return 'sales-agent';
  if(['support','refund','return','complaint'].includes(intent))return 'customer-service-agent';
  if(['payment','invoice','settlement'].includes(intent))return 'payment-agent';
  if(intent==='vip')return 'vip-agent';
  return 'supervisor-agent';
}

export async function migrateSecureKnowledge(){
  await pool.query(`
    create table if not exists ai_agents(
      id uuid primary key default gen_random_uuid(),slug text not null unique,name text not null,description text,department text,agent_type text not null default 'service',status text not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now()
    );
    create table if not exists knowledge_items(
      id uuid primary key default gen_random_uuid(),title text not null,category text not null,department text,source_type text not null default 'manual',authority_level int not null default 3 check(authority_level between 1 and 6),data_class text not null default 'static' check(data_class in ('static','dynamic')),status text not null default 'draft' check(status in ('draft','review','published','archived')),current_version_id uuid,created_by uuid references operators(id),approved_by uuid references operators(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now()
    );
    create table if not exists knowledge_versions(
      id uuid primary key default gen_random_uuid(),item_id uuid not null references knowledge_items(id) on delete cascade,version_no int not null,content text not null,summary text,tags text[] not null default '{}',source_ref text,effective_from timestamptz,expires_at timestamptz,status text not null default 'draft' check(status in ('draft','review','published','archived')),created_by uuid references operators(id),approved_by uuid references operators(id),created_at timestamptz not null default now(),unique(item_id,version_no)
    );
    create table if not exists knowledge_agent_scopes(agent_id uuid not null references ai_agents(id) on delete cascade,item_id uuid not null references knowledge_items(id) on delete cascade,access_mode text not null default 'read',created_at timestamptz not null default now(),primary key(agent_id,item_id));
    create table if not exists knowledge_usage_logs(id uuid primary key default gen_random_uuid(),agent_id uuid references ai_agents(id),operator_id uuid references operators(id),query text not null,retrieval_mode text not null default 'lexical',matched_item_ids uuid[] not null default '{}',evidence jsonb not null default '[]',created_at timestamptz not null default now());
    create table if not exists knowledge_documents(
      id uuid primary key default gen_random_uuid(),filename text not null,mime_type text,source_type text not null default 'upload',status text not null default 'uploaded',text_content text,byte_size int,uploaded_by uuid references operators(id),created_at timestamptz not null default now(),processed_at timestamptz,error text
    );
    create table if not exists knowledge_suggestions(
      id uuid primary key default gen_random_uuid(),conversation_id uuid references conversations(id) on delete set null,title text not null,proposed_content text not null,category text not null default 'FAQ',department text,agent_slug text,status text not null default 'pending' check(status in ('pending','approved','rejected')),source_message_ids uuid[] not null default '{}',suggested_by uuid references operators(id),reviewed_by uuid references operators(id),created_at timestamptz not null default now(),reviewed_at timestamptz
    );
    create table if not exists agent_runtime_logs(
      id uuid primary key default gen_random_uuid(),conversation_id uuid references conversations(id) on delete set null,operator_id uuid references operators(id),agent_id uuid references ai_agents(id),query text not null,response_text text,knowledge_item_ids uuid[] not null default '{}',knowledge_versions jsonb not null default '[]',confidence text not null default 'low',provider text not null default 'fallback',created_at timestamptz not null default now()
    );
    alter table knowledge_items drop constraint if exists knowledge_items_current_version_id_fkey;
    alter table knowledge_items add constraint knowledge_items_current_version_id_fkey foreign key(current_version_id) references knowledge_versions(id) on delete set null;
    create index if not exists idx_knowledge_items_status_category on knowledge_items(status,category,department);
    create index if not exists idx_knowledge_versions_item_status on knowledge_versions(item_id,status,version_no desc);
    create index if not exists idx_knowledge_scope_agent on knowledge_agent_scopes(agent_id,item_id);
    create index if not exists idx_knowledge_docs_status on knowledge_documents(status,created_at desc);
    create index if not exists idx_knowledge_suggestions_status on knowledge_suggestions(status,created_at desc);
  `);
  const seeds=[
    ['sales-agent','Sales Agent','Product, pricing, promotion and sales guidance','Sales'],
    ['customer-service-agent','Customer Service Agent','Support, complaint, return and service policies','Customer Service'],
    ['payment-agent','Payment Agent','Payment, invoice and settlement guidance','Finance'],
    ['vip-agent','VIP Agent','VIP service rules and priority handling','VIP'],
    ['supervisor-agent','Supervisor Agent','Cross-department policy and escalation supervision','Management']
  ];
  for(const s of seeds)await pool.query(`insert into ai_agents(slug,name,description,department) values($1,$2,$3,$4) on conflict(slug) do update set name=excluded.name,description=excluded.description,department=excluded.department,updated_at=now()`,s);
}

export async function retrieveSecureKnowledge(query:string,agentSlug:string,limit=6,operatorId?:string|null){
  const aq=await pool.query('select id,slug,name,department from ai_agents where slug=$1 and status=$2',[agentSlug,'active']);
  const ag=aq.rows[0];if(!ag)return{agent:null,items:[],evidence:[],retrieval_mode:'lexical'};
  const terms=words(query).slice(0,12);
  const all=await pool.query(`select ki.id,ki.title,ki.category,ki.department,ki.authority_level,ki.data_class,kv.id version_id,kv.version_no,kv.content,kv.summary,kv.tags,kv.source_ref,kv.effective_from,kv.expires_at
    from knowledge_agent_scopes kas join knowledge_items ki on ki.id=kas.item_id join knowledge_versions kv on kv.id=ki.current_version_id
    where kas.agent_id=$1 and ki.status='published' and kv.status='published' and (kv.effective_from is null or kv.effective_from<=now()) and (kv.expires_at is null or kv.expires_at>now())`,[ag.id]);
  const scored=all.rows.map((x:any)=>{
    const hay=`${x.title} ${x.summary||''} ${x.content||''} ${(x.tags||[]).join(' ')}`.toLowerCase();
    let score=0;for(const t of terms){if(hay.includes(t))score+=hay.startsWith(t)?3:1}
    score+=(7-Number(x.authority_level||6))*0.35;
    if(x.department&&ag.department&&String(x.department).toLowerCase()===String(ag.department).toLowerCase())score+=1;
    return{...x,_score:score};
  }).filter((x:any)=>x._score>0).sort((a:any,b:any)=>b._score-a._score||a.authority_level-b.authority_level).slice(0,Math.max(1,Math.min(limit,12)));
  const evidence=scored.map((x:any)=>({item_id:x.id,title:x.title,version:x.version_no,authority_level:x.authority_level,category:x.category,source_ref:x.source_ref,excerpt:String(x.content||'').slice(0,1000),score:Number(x._score.toFixed(2))}));
  await pool.query('insert into knowledge_usage_logs(agent_id,operator_id,query,retrieval_mode,matched_item_ids,evidence) values($1,$2,$3,$4,$5,$6)',[ag.id,operatorId||null,query,'lexical-governed',scored.map((x:any)=>x.id),JSON.stringify(evidence)]);
  return{agent:ag,items:scored,evidence,retrieval_mode:'lexical-governed'};
}

async function generateGroundedReply(input:{customerName?:string;intent?:string;customerText:string;operatorText:string;evidence:any[]}){
  const evidenceText=input.evidence.map((e,i)=>`[K${i+1}] ${e.title} v${e.version} (authority ${e.authority_level}): ${e.excerpt}`).join('\n\n');
  const key=process.env.OPENAI_API_KEY;
  if(!key)return{reply:input.operatorText,provider:'fallback'};
  const body={model:process.env.OPENAI_MODEL||'gpt-5.6-luna',input:[{role:'user',content:[{type:'input_text',text:`You are a customer communication rewrite agent. Rewrite the operator draft into concise professional WhatsApp language. Facts may come ONLY from the operator draft and the approved knowledge evidence below. Never invent price, stock, ETA, discount, policy, refund eligibility, payment status, or promises. If knowledge conflicts, prefer lower authority number. If evidence is insufficient, preserve the operator draft and avoid adding facts. Customer: ${input.customerName||'Customer'}\nIntent: ${input.intent||'general'}\nCustomer message: ${input.customerText}\nOperator draft: ${input.operatorText}\n\nApproved knowledge evidence:\n${evidenceText||'(none)'}`}]}],max_output_tokens:260};
  const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${key}`},body:JSON.stringify(body)});
  if(!r.ok)return{reply:input.operatorText,provider:`openai_error_${r.status}`};
  const data:any=await r.json();const text=data.output_text||data.output?.flatMap((o:any)=>o.content||[]).find((c:any)=>c.type==='output_text')?.text;
  return{reply:String(text||input.operatorText).trim(),provider:'openai'};
}

export function registerSecureKnowledgeRoutes(app:Express,deps:Deps){
  const user=(req:Request,res:Response)=>deps.requireUser(req,res);

  app.get('/api/v1/knowledge/dashboard',async(req,res)=>{const u=await user(req,res);if(!u)return;const [items,published,review,agents,usage,suggestions,docs]=await Promise.all([pool.query('select count(*)::int n from knowledge_items'),pool.query("select count(*)::int n from knowledge_items where status='published'"),pool.query("select count(*)::int n from knowledge_items where status='review'"),pool.query("select count(*)::int n from ai_agents where status='active'"),pool.query("select count(*)::int n from knowledge_usage_logs where created_at>now()-interval '24 hours'"),pool.query("select count(*)::int n from knowledge_suggestions where status='pending'"),pool.query('select count(*)::int n from knowledge_documents')]);res.json({items:items.rows[0].n,published:published.rows[0].n,review:review.rows[0].n,agents:agents.rows[0].n,searches24h:usage.rows[0].n,pending_suggestions:suggestions.rows[0].n,documents:docs.rows[0].n})});
  app.get('/api/v1/knowledge/agents',async(req,res)=>{const u=await user(req,res);if(!u)return;const q=await pool.query(`select a.*,count(kas.item_id)::int knowledge_count from ai_agents a left join knowledge_agent_scopes kas on kas.agent_id=a.id group by a.id order by a.name`);res.json({items:q.rows})});
  app.get('/api/v1/knowledge/items',async(req,res)=>{const u=await user(req,res);if(!u)return;const q=await pool.query(`select ki.*,kv.version_no,kv.summary,kv.tags,kv.effective_from,kv.expires_at,coalesce(json_agg(json_build_object('id',ag.id,'slug',ag.slug,'name',ag.name)) filter(where ag.id is not null),'[]') agents from knowledge_items ki left join knowledge_versions kv on kv.id=ki.current_version_id left join knowledge_agent_scopes kas on kas.item_id=ki.id left join ai_agents ag on ag.id=kas.agent_id group by ki.id,kv.id order by ki.updated_at desc limit 500`);res.json({items:q.rows})});
  app.post('/api/v1/knowledge/items',async(req,res)=>{const u=await user(req,res);if(!u)return;if(!['admin','supervisor'].includes(u.role))return res.status(403).json({error:'forbidden'});const title=String(req.body?.title||'').trim(),content=String(req.body?.content||'').trim();if(!title||!content)return res.status(400).json({error:'title_and_content_required'});const client=await pool.connect();try{await client.query('begin');const item=await client.query(`insert into knowledge_items(title,category,department,source_type,authority_level,data_class,status,created_by) values($1,$2,$3,$4,$5,$6,'draft',$7) returning *`,[title,String(req.body?.category||'General'),String(req.body?.department||'').trim()||null,String(req.body?.source_type||'manual'),Math.max(1,Math.min(Number(req.body?.authority_level)||3,6)),req.body?.data_class==='dynamic'?'dynamic':'static',u.id]);const version=await client.query(`insert into knowledge_versions(item_id,version_no,content,summary,tags,source_ref,effective_from,expires_at,status,created_by) values($1,1,$2,$3,$4,$5,$6,$7,'draft',$8) returning *`,[item.rows[0].id,content,String(req.body?.summary||'').trim()||null,arr(req.body?.tags),String(req.body?.source_ref||'').trim()||null,req.body?.effective_from||null,req.body?.expires_at||null,u.id]);await client.query('update knowledge_items set current_version_id=$2 where id=$1',[item.rows[0].id,version.rows[0].id]);for(const agentId of arr(req.body?.agent_ids))await client.query('insert into knowledge_agent_scopes(agent_id,item_id) values($1,$2) on conflict do nothing',[agentId,item.rows[0].id]);await client.query('commit');res.status(201).json({item:item.rows[0],version:version.rows[0]})}catch(e){await client.query('rollback');throw e}finally{client.release()}});
  app.post('/api/v1/knowledge/items/:id/review',async(req,res)=>{const u=await user(req,res);if(!u)return;if(!['admin','supervisor'].includes(u.role))return res.status(403).json({error:'forbidden'});await pool.query("update knowledge_items set status='review',updated_at=now() where id=$1",[req.params.id]);await pool.query("update knowledge_versions set status='review' where id=(select current_version_id from knowledge_items where id=$1)",[req.params.id]);res.json({ok:true})});
  app.post('/api/v1/knowledge/items/:id/publish',async(req,res)=>{const u=await user(req,res);if(!u)return;if(u.role!=='admin')return res.status(403).json({error:'admin_required'});const q=await pool.query('select current_version_id from knowledge_items where id=$1',[req.params.id]);if(!q.rows[0])return res.status(404).json({error:'knowledge_not_found'});await pool.query("update knowledge_versions set status='archived' where item_id=$1 and id<>$2 and status='published'",[req.params.id,q.rows[0].current_version_id]);await pool.query("update knowledge_versions set status='published',approved_by=$2 where id=$1",[q.rows[0].current_version_id,u.id]);await pool.query("update knowledge_items set status='published',approved_by=$2,updated_at=now() where id=$1",[req.params.id,u.id]);res.json({ok:true})});
  app.post('/api/v1/knowledge/search',async(req,res)=>{const u=await user(req,res);if(!u)return;const query=String(req.body?.query||'').trim(),slug=String(req.body?.agent_slug||'supervisor-agent');if(!query)return res.status(400).json({error:'query_required'});res.json(await retrieveSecureKnowledge(query,slug,Number(req.body?.limit)||6,u.id))});

  app.get('/api/v1/knowledge/documents',async(req,res)=>{const u=await user(req,res);if(!u)return;const q=await pool.query('select id,filename,mime_type,status,byte_size,created_at,processed_at,error from knowledge_documents order by created_at desc limit 200');res.json({items:q.rows})});
  app.post('/api/v1/knowledge/documents',async(req,res)=>{const u=await user(req,res);if(!u)return;if(!['admin','supervisor'].includes(u.role))return res.status(403).json({error:'forbidden'});const filename=String(req.body?.filename||'knowledge.txt').trim(),mime=String(req.body?.mime_type||'text/plain'),text=String(req.body?.text_content||'');let status='uploaded',error=null;if(!text&&/pdf|word|officedocument/.test(mime)){status='pending_extraction';error='Binary parser worker not enabled yet';}else if(!text){return res.status(400).json({error:'text_content_required_for_this_file_type'})}const q=await pool.query('insert into knowledge_documents(filename,mime_type,status,text_content,byte_size,uploaded_by,error,processed_at) values($1,$2,$3,$4,$5,$6,$7,case when $3=$8 then now() else null end) returning *',[filename,mime,status,text||null,Buffer.byteLength(text),u.id,error,'uploaded']);res.status(201).json(q.rows[0])});
  app.post('/api/v1/knowledge/documents/:id/create-draft',async(req,res)=>{const u=await user(req,res);if(!u)return;if(!['admin','supervisor'].includes(u.role))return res.status(403).json({error:'forbidden'});const d=await pool.query('select * from knowledge_documents where id=$1',[req.params.id]);if(!d.rows[0]?.text_content)return res.status(409).json({error:'document_text_not_ready'});const agentIds=arr(req.body?.agent_ids);const client=await pool.connect();try{await client.query('begin');const item=await client.query(`insert into knowledge_items(title,category,department,source_type,authority_level,data_class,status,created_by) values($1,$2,$3,'document',$4,'static','draft',$5) returning *`,[String(req.body?.title||d.rows[0].filename),String(req.body?.category||'Document'),String(req.body?.department||'').trim()||null,Math.max(1,Math.min(Number(req.body?.authority_level)||3,6)),u.id]);const v=await client.query(`insert into knowledge_versions(item_id,version_no,content,summary,tags,source_ref,status,created_by) values($1,1,$2,$3,$4,$5,'draft',$6) returning *`,[item.rows[0].id,d.rows[0].text_content,String(req.body?.summary||'Imported document'),arr(req.body?.tags),`document:${d.rows[0].id}`,u.id]);await client.query('update knowledge_items set current_version_id=$2 where id=$1',[item.rows[0].id,v.rows[0].id]);for(const id of agentIds)await client.query('insert into knowledge_agent_scopes(agent_id,item_id) values($1,$2) on conflict do nothing',[id,item.rows[0].id]);await client.query('update knowledge_documents set status=$2,processed_at=now(),error=null where id=$1',[d.rows[0].id,'draft_created']);await client.query('commit');res.status(201).json({item:item.rows[0],version:v.rows[0]})}catch(e){await client.query('rollback');throw e}finally{client.release()}});

  app.get('/api/v1/knowledge/suggestions',async(req,res)=>{const u=await user(req,res);if(!u)return;const q=await pool.query('select ks.*,o.name suggested_by_name,r.name reviewed_by_name from knowledge_suggestions ks left join operators o on o.id=ks.suggested_by left join operators r on r.id=ks.reviewed_by order by ks.created_at desc limit 300');res.json({items:q.rows})});
  app.post('/api/v1/conversations/:id/knowledge-suggestion',async(req,res)=>{const u=await user(req,res);if(!u)return;const title=String(req.body?.title||'').trim(),content=String(req.body?.content||'').trim();if(!title||!content)return res.status(400).json({error:'title_and_content_required'});const cv=await pool.query('select intent,wa.department from conversations cv join whatsapp_accounts wa on wa.id=cv.whatsapp_account_id where cv.id=$1',[req.params.id]);if(!cv.rows[0])return res.status(404).json({error:'conversation_not_found'});const slug=String(req.body?.agent_slug||agentForIntent(cv.rows[0].intent||'general'));const q=await pool.query(`insert into knowledge_suggestions(conversation_id,title,proposed_content,category,department,agent_slug,suggested_by) values($1,$2,$3,$4,$5,$6,$7) returning *`,[req.params.id,title,content,String(req.body?.category||'FAQ'),cv.rows[0].department||null,slug,u.id]);res.status(201).json(q.rows[0])});
  app.post('/api/v1/knowledge/suggestions/:id/review',async(req,res)=>{const u=await user(req,res);if(!u)return;if(!['admin','supervisor'].includes(u.role))return res.status(403).json({error:'forbidden'});const action=String(req.body?.action||'');if(!['approve','reject'].includes(action))return res.status(400).json({error:'action_required'});const s=await pool.query('select * from knowledge_suggestions where id=$1 and status=$2',[req.params.id,'pending']);if(!s.rows[0])return res.status(404).json({error:'suggestion_not_found'});if(action==='reject'){await pool.query("update knowledge_suggestions set status='rejected',reviewed_by=$2,reviewed_at=now() where id=$1",[req.params.id,u.id]);return res.json({ok:true,status:'rejected'})}const ag=await pool.query('select id from ai_agents where slug=$1',[s.rows[0].agent_slug]);const client=await pool.connect();try{await client.query('begin');const item=await client.query(`insert into knowledge_items(title,category,department,source_type,authority_level,data_class,status,created_by) values($1,$2,$3,'conversation_suggestion',5,'static','draft',$4) returning *`,[s.rows[0].title,s.rows[0].category,s.rows[0].department,u.id]);const v=await client.query(`insert into knowledge_versions(item_id,version_no,content,summary,source_ref,status,created_by) values($1,1,$2,$3,$4,'draft',$5) returning *`,[item.rows[0].id,s.rows[0].proposed_content,'Suggested from a real customer conversation',`conversation:${s.rows[0].conversation_id}`,u.id]);await client.query('update knowledge_items set current_version_id=$2 where id=$1',[item.rows[0].id,v.rows[0].id]);if(ag.rows[0])await client.query('insert into knowledge_agent_scopes(agent_id,item_id) values($1,$2) on conflict do nothing',[ag.rows[0].id,item.rows[0].id]);await client.query("update knowledge_suggestions set status='approved',reviewed_by=$2,reviewed_at=now() where id=$1",[req.params.id,u.id]);await client.query('commit');res.json({ok:true,status:'approved',knowledge_item_id:item.rows[0].id})}catch(e){await client.query('rollback');throw e}finally{client.release()}});

  app.post('/api/v1/conversations/:id/operator-preview',async(req,res)=>{const u=await user(req,res);if(!u)return;const operatorText=String(req.body?.text||'').trim();if(!operatorText)return res.status(400).json({error:'text_required'});const cvq=await pool.query(`select cv.id,cv.intent,cv.assigned_operator_id,c.name customer_name,c.phone customer_phone,wa.department from conversations cv join customers c on c.id=cv.customer_id join whatsapp_accounts wa on wa.id=cv.whatsapp_account_id where cv.id=$1`,[req.params.id]);const cv=cvq.rows[0];if(!cv)return res.status(404).json({error:'conversation_not_found'});if(u.role==='operator'&&cv.assigned_operator_id&&cv.assigned_operator_id!==u.id)return res.status(403).json({error:'conversation_assigned_to_another_operator'});const last=await pool.query("select id,original_text from messages where conversation_id=$1 and direction='inbound' order by created_at desc limit 1",[cv.id]);const customerText=String(last.rows[0]?.original_text||'');const slug=String(req.body?.agent_slug||agentForIntent(cv.intent||'general'));const retrieval=await retrieveSecureKnowledge(`${customerText} ${operatorText}`,slug,6,u.id);const generated=await generateGroundedReply({customerName:cv.customer_name,intent:cv.intent,customerText,operatorText,evidence:retrieval.evidence});const confidence=retrieval.evidence.length>=2?'high':retrieval.evidence.length===1?'medium':'low';const log=await pool.query(`insert into agent_runtime_logs(conversation_id,operator_id,agent_id,query,response_text,knowledge_item_ids,knowledge_versions,confidence,provider) values($1,$2,$3,$4,$5,$6,$7,$8,$9) returning id`,[cv.id,u.id,retrieval.agent?.id||null,`${customerText} ${operatorText}`,generated.reply,retrieval.evidence.map((e:any)=>e.item_id),JSON.stringify(retrieval.evidence.map((e:any)=>({item_id:e.item_id,version:e.version,title:e.title,authority_level:e.authority_level}))),confidence,generated.provider]);res.json({original_text:operatorText,rewritten_text:generated.reply,ai_available:Boolean(process.env.OPENAI_API_KEY),agent:retrieval.agent,knowledge_used:retrieval.evidence,confidence,runtime_log_id:log.rows[0].id,provider:generated.provider})});
  app.get('/api/v1/conversations/:id/agent-traces',async(req,res)=>{const u=await user(req,res);if(!u)return;const q=await pool.query(`select l.*,a.slug agent_slug,a.name agent_name,o.name operator_name from agent_runtime_logs l left join ai_agents a on a.id=l.agent_id left join operators o on o.id=l.operator_id where l.conversation_id=$1 order by l.created_at desc limit 50`,[req.params.id]);res.json({items:q.rows})});
}
