import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import Papa from'papaparse';
import{Activity,Bot,ChevronDown,Database,FileUp,Inbox,LayoutDashboard,MessageCircleMore,MoreHorizontal,Plus,Search,Send,Settings,UsersRound,Wifi,BarChart3,X,CheckCircle2,Sparkles}from'lucide-react';
import'./styles.css';
type Nav='Dashboard'|'Inbox'|'Customers'|'WhatsApp Numbers'|'AI Agents'|'Campaigns'|'Analytics'|'Settings';type Row=Record<string,any>;
const nav:[Nav,React.ReactNode][]=[['Dashboard',<LayoutDashboard/>],['Inbox',<Inbox/>],['Customers',<UsersRound/>],['WhatsApp Numbers',<MessageCircleMore/>],['AI Agents',<Bot/>],['Campaigns',<Send/>],['Analytics',<BarChart3/>],['Settings',<Settings/>]];
function Pill({children,tone='neutral'}:{children:React.ReactNode,tone?:string}){return <span className={'pill '+tone}>{children}</span>};
function Card({icon,label,value,sub}:{icon:React.ReactNode,label:string,value:string,sub:string}){return <div className="card"><div className="icon">{icon}</div><span>{label}</span><div><b>{value}</b><small>{sub}</small></div></div>};
function Panel({title,children}:{title:string,children:React.ReactNode}){return <section className="panel"><header><h3>{title}</h3><button>Live data</button></header>{children}</section>};
function App(){const[active,setActive]=useState<Nav>('Dashboard'),[open,setOpen]=useState(false),[rows,setRows]=useState<Row[]>([]),[file,setFile]=useState(''),[numbers,setNumbers]=useState<any[]>([]),[customers,setCustomers]=useState<any[]>([]),[convos,setConvos]=useState<any[]>([]),[dash,setDash]=useState<any>(null),[importing,setImporting]=useState(false),[notice,setNotice]=useState('');const ref=useRef<HTMLInputElement>(null);
async function load(){const safe=async(u:string)=>{const r=await fetch(u);return r.ok?r.json():null};const[n,c,v,d]=await Promise.all([safe('/api/v1/numbers'),safe('/api/v1/customers'),safe('/api/v1/conversations'),safe('/api/v1/dashboard')]);if(n?.items)setNumbers(n.items);if(c?.items)setCustomers(c.items);if(v?.items)setConvos(v.items);if(d)setDash(d)}
useEffect(()=>{load()},[]);
const stats=useMemo(()=>{if(!rows.length)return null;const phones=rows.map(r=>String(r.phone??r.mobile??r.mobile_number??r.whatsapp??'').replace(/\D/g,'')).map(x=>x.startsWith('0')?'62'+x.slice(1):x.startsWith('8')?'62'+x:x);const valid=phones.filter(x=>/^62\d{8,13}$/.test(x));return{total:rows.length,valid:valid.length,duplicates:valid.length-new Set(valid).size,invalid:rows.length-valid.length}},[rows]);
function parse(f?:File){if(!f)return;setFile(f.name);Papa.parse<Row>(f,{header:true,skipEmptyLines:true,complete:r=>setRows(r.data.map((x:any)=>({...x,phone:x.phone??x.mobile??x.mobile_number??x.whatsapp})))})}
async function importRows(){setImporting(true);setNotice('');try{const r=await fetch('/api/v1/customers/import',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({rows})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Import failed');setNotice(`Imported ${d.inserted} new · updated ${d.updated} · invalid ${d.invalid}`);await load();setRows([]);setFile('')}catch(e:any){setNotice(e.message)}finally{setImporting(false)}}
const chats=convos.length?convos.slice(0,6):[];
return <div className="shell"><aside className="sidebar"><div className="brand"><div>R</div><span><b>RelayOS</b><small>AI Communication Hub</small></span></div><div className="workspace"><div className="avatar">NX</div><span><b>Production</b><small>Live workspace</small></span><ChevronDown/></div><nav>{nav.map(([n,ic])=><button className={active===n?'active':''} key={n} onClick={()=>setActive(n)}>{ic}<span>{n}</span>{n==='Inbox'&&<i>{convos.length}</i>}</button>)}</nav><div className="system"><span><Wifi/>System status</span><Pill tone="green">API live</Pill><div><i/></div><small>{numbers.length} numbers · {customers.length} loaded customers</small></div><div className="user"><div className="avatar">AD</div><span><b>Adwin</b><small>Administrator</small></span><MoreHorizontal/></div></aside><main><header className="topbar"><div><small>WORKSPACE / {active.toUpperCase()}</small><h1>{active}</h1></div><div><label className="search"><Search/><input placeholder="Search customers, chats..."/></label><button className="round" onClick={load}><Activity/></button><button className="primary" onClick={()=>setOpen(true)}><FileUp/>Import customers</button></div></header>
{active==='Dashboard'&&<><section className="hero"><div><Pill tone="purple">Production data layer</Pill><h2>One command center for every WhatsApp conversation.</h2><p>Customers, official sender channels, conversations, messages and routing now read from the RelayOS API.</p><div className="hero-actions"><button className="primary" onClick={()=>setOpen(true)}><FileUp/>Import customers</button><button className="secondary" onClick={()=>setActive('WhatsApp Numbers')}><Plus/>Add WhatsApp number</button></div></div><div className="orb"><span>{numbers.length?Math.round(numbers.reduce((a,n)=>a+Number(n.health||0),0)/numbers.length):'—'}</span><small>Avg health</small></div></section><div className="stats"><Card icon={<MessageCircleMore/>} label="Connected numbers" value={String(dash?.numbers?.total??numbers.length)} sub={`${dash?.numbers?.healthy??0} healthy`}/><Card icon={<Inbox/>} label="Open conversations" value={String(dash?.conversations?.open??convos.length)} sub="Live queue"/><Card icon={<UsersRound/>} label="Customers" value={String(dash?.customers?.total??customers.length)} sub={`${dash?.customers?.opted_in??0} opted in`}/><Card icon={<Bot/>} label="Messages 24h" value={String(dash?.messages24h??0)} sub="Persisted events"/></div><div className="grid"><Panel title="Live conversations">{chats.length?chats.map(c=><div className="chat-row" key={c.id}><div className="avatar">{(c.customer_name||'C').slice(0,2).toUpperCase()}</div><div><b>{c.customer_name||c.customer_phone}</b><span>{c.last_message||'No messages yet'}</span></div><div><Pill>{c.channel_name}</Pill><small>{c.intent||'general'}</small></div></div>):<p className="empty">No live conversations yet. Meta webhook traffic will appear here.</p>}</Panel><Panel title="Number health">{numbers.length?numbers.map(n=><div className="health-row" key={n.id}><i className={Number(n.health)<80?'warn':''}/><div><b>{n.name}</b><span>{n.phone}</span></div><strong>{n.health}</strong></div>):<p className="empty">Add your first WhatsApp Business number.</p>}</Panel></div></>}
{active==='Customers'&&<><div className="section-head"><div><h2>Customers</h2><p>Normalized, deduplicated and consent-aware customer database.</p></div><button className="primary" onClick={()=>setOpen(true)}><FileUp/>Import CSV</button></div><Panel title="Customer database"><div className="table head"><span>Customer</span><span>WhatsApp</span><span>Opt-in</span><span>Assigned sender</span><span>Status</span></div>{customers.map(c=><div className="table" key={c.id}><span>{c.name||'Unnamed customer'}</span><span>{c.phone}</span><span><Pill tone={c.opt_in?'green':'amber'}>{c.opt_in?'Yes':'No'}</Pill></span><span>{c.assigned_sender||'Unassigned'}</span><span>{c.do_not_contact?'Blocked':'Active'}</span></div>)}</Panel></>}
{active==='WhatsApp Numbers'&&<><div className="section-head"><div><h2>WhatsApp Numbers</h2><p>Official sender channels, sticky routing modes and health signals.</p></div><button className="primary"><Plus/>Add number via API</button></div><div className="number-grid">{numbers.map(n=><div className="number-card" key={n.id}><div className="wa-icon"><MessageCircleMore/></div><Pill tone={Number(n.health)<80?'amber':'green'}>{n.status}</Pill><h3>{n.name}</h3><p>{n.phone}</p><div className="score"><div><span>Health score</span><b>{n.health}</b></div><div className="ring" style={{'--score':n.health+'%'} as React.CSSProperties}/></div><div className="meta"><span>Open chats <b>{n.chats}</b></span><span>Mode <b>{n.mode}</b></span></div></div>)}</div></>}
{active==='Inbox'&&<div className="inbox-shell"><aside>{chats.map((c,i)=><button className={'chat-item '+(i===0?'selected':'')} key={c.id}><div className="avatar">{(c.customer_name||'C').slice(0,2).toUpperCase()}</div><div><b>{c.customer_name||c.customer_phone}</b><span>{c.last_message||'No message'}</span><small>{c.channel_name} · {c.intent||'general'}</small></div></button>)}</aside><section className="conversation"><header><div className="avatar">AI</div><div><b>Relay inbox</b><span>Persisted conversations from Meta webhook</span></div><Pill tone="purple">Live backend</Pill></header><div className="messages"><div className="ai-note"><Sparkles/>Select a conversation to continue operator relay. Message persistence is active.</div></div></section></div>}
{active==='AI Agents'&&<div className="agent-grid">{[['Supervisor Agent','Coordinates intent, routing and escalation.'],['Rewrite Agent','Transforms operator shorthand into brand-safe replies.'],['Routing Agent','Locks customers to the correct healthy sender.'],['Safety Agent','Preserves facts and keeps outbound behind policy gates.']].map((a,i)=><div className="agent" key={a[0]}><div className="agent-icon"><Bot/></div><Pill tone="green">Active</Pill><h3>{a[0]}</h3><p>{a[1]}</p><small>Policy v2.{i+1}</small></div>)}</div>}
{['Campaigns','Analytics','Settings'].includes(active)&&<div className="placeholder"><div className="agent-icon"><Activity/></div><h2>{active}</h2><p>This module is connected to the production information architecture and ready for the next slice.</p></div>}</main>
{open&&<div className="backdrop" onMouseDown={()=>setOpen(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setOpen(false)}><X/></button><div className="modal-icon"><Database/></div><h2>Import customer database</h2><p>Upload CSV. Indonesian numbers are normalized to <b>62…</b> without a plus sign and deduplicated by phone.</p><div className="drop" onClick={()=>ref.current?.click()}><FileUp/><b>{file||'Choose CSV file'}</b><span>phone / mobile / mobile_number / whatsapp</span><input ref={ref} hidden type="file" accept=".csv" onChange={e=>parse(e.target.files?.[0])}/></div>{stats&&<div className="import-stats"><div><span>Total rows</span><b>{stats.total}</b></div><div><span>Valid</span><b>{stats.valid}</b></div><div><span>Duplicates</span><b>{stats.duplicates}</b></div><div><span>Invalid</span><b>{stats.invalid}</b></div></div>}{notice&&<div className="example"><span>Import result</span><code>{notice}</code></div>}<div className="actions"><button className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="primary" disabled={!stats||importing} onClick={importRows}><CheckCircle2/>{importing?'Importing…':'Import valid records'}</button></div></div></div>}</div>}
createRoot(document.getElementById('root')!).render(<App/>);